services:
  server:
    build:
      context: ../apps/server
      dockerfile: Dockerfile.dev
      target: backend-dev
    image: godploy-backend-dev
    container_name: godploy-backend-dev
    develop:
      watch:
        - action: sync
          path: ../apps/server
          target: /app/server
          initial_sync: true
          ignore:
            - bin
            - data
        - action: rebuild
          path: ../apps/server/go.mod
        - action: rebuild
          path: ../apps/server/go.sum
        - action: rebuild
          path: ../apps/server/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../apps/server/.env:/app/server/.env:rw
      - godploy-dev-data:/app/server/data/sqlite
      - godploy-dev-logs:/app/server/data/badger
      - godploy-dev-codebase:/etc/godploy/code
    environment:
      - JWT_SECRET=red_balloon
      - APP_ENV=development
      - WEB_URL=http://localhost:3000
    ports:
      - "8080:8080"
    working_dir: /app/server
    restart: unless-stopped
    networks:
      - godploy-dev

networks:
  godploy-dev:
    attachable: true

volumes:
  godploy-dev-data:
    name: godploy-dev-data
  godploy-dev-logs:
    name: godploy-dev-logs
  godploy-dev-codebase:
    name: godploy-dev-codebase
