services:
  web:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
      target: frontend-dev
    image: godploy-frontend-dev
    container_name: godploy-frontend-dev
    develop:
      watch:
        - action: sync
          path: ../frontend
          target: /app/frontend
          ignore:
            - node_modules/
            - .svelte-kit/
            - build/
        - action: rebuild
          path: ../frontend/package.json
        - action: rebuild
          path: ../frontend/bun.lock
    volumes:
      - ../frontend/.svelte-kit:/app/frontend/.svelte-kit:rw
    environment:
      - NODE_ENV=development
      - DEV_BACKEND_URL=http://server:8080
    user: "bun"
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - godploy-dev

  server:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
      target: backend-dev
    image: godploy-backend-dev
    container_name: godploy-backend-dev
    develop:
      watch:
        - action: rebuild
          path: ../backend/go.mod
        - action: rebuild
          path: ../backend/go.sum
        - action: rebuild
          path: ../.env
    volumes:
      - ../backend:/app/backend
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.env:/app/backend/.env:rw
      - godploy-dev-data:/app/backend/data/sqlite
      - godploy-dev-logs:/app/backend/data/badger
      - godploy-dev-codebase:/etc/godploy/code
    environment:
      - JWT_SECRET=red_balloon
      - APP_ENV=dev
      - WEB_URL=http://localhost:3000
    ports:
      - "8080:8080"
    working_dir: /app/backend
    restart: unless-stopped
    networks:
      - godploy-dev

networks:
  godploy-dev:
    attachable: true

volumes:
  godploy-dev-data:
    name: godploy-dev-data
  godploy-dev-logs:
    name: godploy-dev-logs
  godploy-dev-codebase:
    name: godploy-dev-codebase
