// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dependency.sql

package db

import (
	"context"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const createServiceDependency = `-- name: CreateServiceDependency :one
INSERT INTO service_dependencies (
    id, source_service_id, target_service_id, target_col, env_key, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, datetime('now'), datetime('now')
)
RETURNING id, source_service_id, target_service_id, target_col, env_key, created_at, updated_at
`

type CreateServiceDependencyParams struct {
	ID              uuid.UUID                 `json:"id"`
	SourceServiceID uuid.UUID                 `json:"source_service_id"`
	TargetServiceID uuid.UUID                 `json:"target_service_id"`
	TargetCol       types.DependencyTargetCol `json:"target_col"`
	EnvKey          string                    `json:"env_key"`
}

func (q *Queries) CreateServiceDependency(ctx context.Context, arg CreateServiceDependencyParams) (ServiceDependency, error) {
	row := q.db.QueryRowContext(ctx, createServiceDependency,
		arg.ID,
		arg.SourceServiceID,
		arg.TargetServiceID,
		arg.TargetCol,
		arg.EnvKey,
	)
	var i ServiceDependency
	err := row.Scan(
		&i.ID,
		&i.SourceServiceID,
		&i.TargetServiceID,
		&i.TargetCol,
		&i.EnvKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIncomingDependencies = `-- name: DeleteIncomingDependencies :exec
DELETE FROM service_dependencies WHERE target_service_id = ?
`

func (q *Queries) DeleteIncomingDependencies(ctx context.Context, targetServiceID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteIncomingDependencies, targetServiceID)
	return err
}

const deleteServiceDependency = `-- name: DeleteServiceDependency :exec
DELETE FROM service_dependencies WHERE id = ?
`

func (q *Queries) DeleteServiceDependency(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteServiceDependency, id)
	return err
}

const getDependenciesByTarget = `-- name: GetDependenciesByTarget :many
SELECT id, source_service_id, target_service_id, target_col, env_key, created_at, updated_at FROM service_dependencies WHERE target_service_id = ?
`

func (q *Queries) GetDependenciesByTarget(ctx context.Context, targetServiceID uuid.UUID) ([]ServiceDependency, error) {
	rows, err := q.db.QueryContext(ctx, getDependenciesByTarget, targetServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDependency
	for rows.Next() {
		var i ServiceDependency
		if err := rows.Scan(
			&i.ID,
			&i.SourceServiceID,
			&i.TargetServiceID,
			&i.TargetCol,
			&i.EnvKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependencyGraphEdges = `-- name: GetDependencyGraphEdges :many
SELECT
    d.source_service_id,
    d.target_service_id,
    d.env_key,
    d.target_col
FROM service_dependencies d
JOIN app_service source ON source.id = d.source_service_id
WHERE source.instance_id = ?
`

type GetDependencyGraphEdgesRow struct {
	SourceServiceID uuid.UUID                 `json:"source_service_id"`
	TargetServiceID uuid.UUID                 `json:"target_service_id"`
	EnvKey          string                    `json:"env_key"`
	TargetCol       types.DependencyTargetCol `json:"target_col"`
}

func (q *Queries) GetDependencyGraphEdges(ctx context.Context, instanceID uuid.UUID) ([]GetDependencyGraphEdgesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDependencyGraphEdges, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDependencyGraphEdgesRow
	for rows.Next() {
		var i GetDependencyGraphEdgesRow
		if err := rows.Scan(
			&i.SourceServiceID,
			&i.TargetServiceID,
			&i.EnvKey,
			&i.TargetCol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependencyGraphNodes = `-- name: GetDependencyGraphNodes :many
SELECT id, name, 'app' as service_type FROM app_service AS a WHERE a.instance_id = ?
UNION ALL
SELECT id, name, 'psql' as service_type FROM psql_service AS p WHERE p.instance_id = ?
UNION ALL
SELECT id, name, 'redis' as service_type FROM redis_service AS r WHERE r.instance_id = ?
`

type GetDependencyGraphNodesParams struct {
	InstanceID   uuid.UUID `json:"instance_id"`
	InstanceID_2 uuid.UUID `json:"instance_id_2"`
	InstanceID_3 uuid.UUID `json:"instance_id_3"`
}

type GetDependencyGraphNodesRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	ServiceType string    `json:"service_type"`
}

func (q *Queries) GetDependencyGraphNodes(ctx context.Context, arg GetDependencyGraphNodesParams) ([]GetDependencyGraphNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDependencyGraphNodes, arg.InstanceID, arg.InstanceID_2, arg.InstanceID_3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDependencyGraphNodesRow
	for rows.Next() {
		var i GetDependencyGraphNodesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ServiceType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependencyTargets = `-- name: GetDependencyTargets :many
SELECT id, 'app' AS service_type, name FROM app_service
WHERE app_service.instance_id = ?1 AND app_service.id != ?2
UNION ALL
SELECT id, 'psql' AS service_type, name FROM psql_service
WHERE psql_service.instance_id = ?1
UNION ALL
SELECT id, 'redis' AS service_type, name FROM redis_service
WHERE redis_service.instance_id = ?1
`

type GetDependencyTargetsParams struct {
	InstanceID uuid.UUID `json:"instance_id"`
	ID         uuid.UUID `json:"id"`
}

type GetDependencyTargetsRow struct {
	ID          uuid.UUID `json:"id"`
	ServiceType string    `json:"service_type"`
	Name        string    `json:"name"`
}

func (q *Queries) GetDependencyTargets(ctx context.Context, arg GetDependencyTargetsParams) ([]GetDependencyTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDependencyTargets, arg.InstanceID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDependencyTargetsRow
	for rows.Next() {
		var i GetDependencyTargetsRow
		if err := rows.Scan(&i.ID, &i.ServiceType, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceDependencies = `-- name: GetServiceDependencies :many
WITH targets AS (
    SELECT id, 'app' AS service_type, name FROM app_service
    UNION ALL
    SELECT id, 'psql' AS service_type, name FROM psql_service
    UNION ALL
    SELECT id, 'redis' AS service_type, name FROM redis_service
)
SELECT
    d.id,
    d.source_service_id,
    d.target_service_id,
    d.target_col,
    d.env_key,
    t.service_type AS target_service_type,
    t.name AS target_service_name,
    d.created_at,
    d.updated_at
FROM service_dependencies d
JOIN targets t ON t.id = d.target_service_id
WHERE d.source_service_id = ?
ORDER BY d.created_at DESC
`

type GetServiceDependenciesRow struct {
	ID                uuid.UUID                 `json:"id"`
	SourceServiceID   uuid.UUID                 `json:"source_service_id"`
	TargetServiceID   uuid.UUID                 `json:"target_service_id"`
	TargetCol         types.DependencyTargetCol `json:"target_col"`
	EnvKey            string                    `json:"env_key"`
	TargetServiceType string                    `json:"target_service_type"`
	TargetServiceName string                    `json:"target_service_name"`
	CreatedAt         time.Time                 `json:"created_at"`
	UpdatedAt         time.Time                 `json:"updated_at"`
}

func (q *Queries) GetServiceDependencies(ctx context.Context, sourceServiceID uuid.UUID) ([]GetServiceDependenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, getServiceDependencies, sourceServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServiceDependenciesRow
	for rows.Next() {
		var i GetServiceDependenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceServiceID,
			&i.TargetServiceID,
			&i.TargetCol,
			&i.EnvKey,
			&i.TargetServiceType,
			&i.TargetServiceName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceDependencyByID = `-- name: GetServiceDependencyByID :one
SELECT id, source_service_id, target_service_id, target_col, env_key, created_at, updated_at FROM service_dependencies WHERE id = ?
`

func (q *Queries) GetServiceDependencyByID(ctx context.Context, id uuid.UUID) (ServiceDependency, error) {
	row := q.db.QueryRowContext(ctx, getServiceDependencyByID, id)
	var i ServiceDependency
	err := row.Scan(
		&i.ID,
		&i.SourceServiceID,
		&i.TargetServiceID,
		&i.TargetCol,
		&i.EnvKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveDependencyEnv = `-- name: ResolveDependencyEnv :many
WITH dependency_targets AS (
    SELECT
        id,
        instance_id,
        'app' AS service_type,
        name,
        internal_url,
        domain,
        '' AS db_name,
        '' AS db_user,
        '' AS db_password,
        '' AS password
    FROM app_service

    UNION ALL

    SELECT
        id,
        instance_id,
        'psql' AS service_type,
        name,
        internal_url,
        '' AS domain,
        db_name,
        db_user,
        db_password,
        '' AS password
    FROM psql_service

    UNION ALL

    SELECT
        id,
        instance_id,
        'redis' AS service_type,
        name,
        internal_url,
        '' AS domain,
        '' AS db_name,
        '' AS db_user,
        '' AS db_password,
        password
    FROM redis_service
)
SELECT
    d.env_key,
    CASE d.target_col
        WHEN 'internal_url' THEN t.internal_url
        WHEN 'domain' THEN t.domain
        WHEN 'db_name' THEN t.db_name
        WHEN 'db_user' THEN t.db_user
        WHEN 'db_password' THEN t.db_password
        WHEN 'password' THEN t.password
        WHEN 'name' THEN t.name
    END AS resolved_value
FROM service_dependencies d
JOIN app_service source ON source.id = d.source_service_id
JOIN dependency_targets t ON t.id = d.target_service_id
WHERE d.source_service_id = ?
  AND t.instance_id = source.instance_id
`

type ResolveDependencyEnvRow struct {
	EnvKey        string      `json:"env_key"`
	ResolvedValue interface{} `json:"resolved_value"`
}

func (q *Queries) ResolveDependencyEnv(ctx context.Context, sourceServiceID uuid.UUID) ([]ResolveDependencyEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, resolveDependencyEnv, sourceServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveDependencyEnvRow
	for rows.Next() {
		var i ResolveDependencyEnvRow
		if err := rows.Scan(&i.EnvKey, &i.ResolvedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceDependency = `-- name: UpdateServiceDependency :one
UPDATE service_dependencies
SET target_service_id = ?, target_col = ?, env_key = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, source_service_id, target_service_id, target_col, env_key, created_at, updated_at
`

type UpdateServiceDependencyParams struct {
	TargetServiceID uuid.UUID                 `json:"target_service_id"`
	TargetCol       types.DependencyTargetCol `json:"target_col"`
	EnvKey          string                    `json:"env_key"`
	ID              uuid.UUID                 `json:"id"`
}

func (q *Queries) UpdateServiceDependency(ctx context.Context, arg UpdateServiceDependencyParams) (ServiceDependency, error) {
	row := q.db.QueryRowContext(ctx, updateServiceDependency,
		arg.TargetServiceID,
		arg.TargetCol,
		arg.EnvKey,
		arg.ID,
	)
	var i ServiceDependency
	err := row.Scan(
		&i.ID,
		&i.SourceServiceID,
		&i.TargetServiceID,
		&i.TargetCol,
		&i.EnvKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
