// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: base.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkInstanceExists = `-- name: CheckInstanceExists :one
SELECT CAST(EXISTS(
    SELECT 1
    FROM instance
    WHERE project_id = ? AND name = ?
) AS BOOLEAN)
`

type CheckInstanceExistsParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	InstanceName string    `json:"instance_name"`
}

func (q *Queries) CheckInstanceExists(ctx context.Context, arg CheckInstanceExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkInstanceExists, arg.ProjectID, arg.InstanceName)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkInstanceHasServices = `-- name: CheckInstanceHasServices :one
SELECT CAST(EXISTS(
    SELECT 1
    FROM app_service aps
    WHERE aps.instance_id = ?1
    UNION ALL
    SELECT 1
    FROM psql_service ps
    where ps.instance_id = ?1
) AS BOOLEAN)
`

func (q *Queries) CheckInstanceHasServices(ctx context.Context, instanceID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkInstanceHasServices, instanceID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkOrgExists = `-- name: CheckOrgExists :one
SELECT CAST(EXISTS(
    SELECT 1 FROM organization o
    JOIN user_organization uo ON o.id = uo.organization_id
    WHERE uo.user_email = ? AND o.name = ?
) AS BOOLEAN)
`

type CheckOrgExistsParams struct {
	UserEmail string `json:"user_email"`
	OrgName   string `json:"org_name"`
}

func (q *Queries) CheckOrgExists(ctx context.Context, arg CheckOrgExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkOrgExists, arg.UserEmail, arg.OrgName)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkProjectExists = `-- name: CheckProjectExists :one
SELECT CAST(EXISTS(
    SELECT 1
    FROM project
    WHERE organization_id = ? AND name = ?
) AS BOOLEAN)
`

type CheckProjectExistsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectName    string    `json:"project_name"`
}

func (q *Queries) CheckProjectExists(ctx context.Context, arg CheckProjectExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectExists, arg.OrganizationID, arg.ProjectName)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkProjectHasInstance = `-- name: CheckProjectHasInstance :one
SELECT CAST(EXISTS(
    SELECT 1
    FROM instance
    WHERE project_id = ?
) AS BOOLEAN)
`

func (q *Queries) CheckProjectHasInstance(ctx context.Context, projectID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectHasInstance, projectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkUserOrgExists = `-- name: CheckUserOrgExists :one
SELECT CAST(EXISTS(
    SELECT 1 FROM user_organization uo
    WHERE uo.user_email = ? AND uo.organization_id = ?
)AS BOOLEAN)
`

type CheckUserOrgExistsParams struct {
	UserEmail      string    `json:"user_email"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) CheckUserOrgExists(ctx context.Context, arg CheckUserOrgExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserOrgExists, arg.UserEmail, arg.OrganizationID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserOrgs = `-- name: CountUserOrgs :one
SELECT COUNT(*) FROM organization
`

func (q *Queries) CountUserOrgs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserOrgs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInstance = `-- name: CreateInstance :exec
INSERT INTO instance (id, project_id, is_production, name, network)
VALUES (?, ?, ?, ?, ?)
`

type CreateInstanceParams struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"project_id"`
	IsProduction bool      `json:"is_production"`
	Name         string    `json:"name"`
	Network      string    `json:"network"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) error {
	_, err := q.db.ExecContext(ctx, createInstance,
		arg.ID,
		arg.ProjectID,
		arg.IsProduction,
		arg.Name,
		arg.Network,
	)
	return err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO organization (id, name)
VALUES (?, ?)
RETURNING id, name
`

type CreateOrgParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type CreateOrgRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (CreateOrgRow, error) {
	row := q.db.QueryRowContext(ctx, createOrg, arg.ID, arg.Name)
	var i CreateOrgRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (id, organization_id, name)
VALUES (?, ?, ?)
RETURNING id, name, created_at
`

type CreateProjectParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
}

type CreateProjectRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.ID, arg.OrganizationID, arg.Name)
	var i CreateProjectRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instance
WHERE id = ?
`

func (q *Queries) DeleteInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInstance, id)
	return err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM organization
WHERE id = ?
`

func (q *Queries) DeleteOrg(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrg, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getAllInstance = `-- name: GetAllInstance :many
SELECT i.id, i.name, i.is_production
FROM instance i
JOIN project p ON i.project_id = p.id
WHERE p.organization_id = ? AND p.name = ?
`

type GetAllInstanceParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Project        string    `json:"project"`
}

type GetAllInstanceRow struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	IsProduction bool      `json:"is_production"`
}

func (q *Queries) GetAllInstance(ctx context.Context, arg GetAllInstanceParams) ([]GetAllInstanceRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllInstance, arg.OrganizationID, arg.Project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllInstanceRow
	for rows.Next() {
		var i GetAllInstanceRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsProduction); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllNetworksByProjectId = `-- name: GetAllNetworksByProjectId :many
SELECT network
FROM instance
WHERE project_id = ?
`

func (q *Queries) GetAllNetworksByProjectId(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllNetworksByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var network string
		if err := rows.Scan(&network); err != nil {
			return nil, err
		}
		items = append(items, network)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOrg = `-- name: GetAllOrg :many
SELECT o.id,o.name
FROM organization o
JOIN user_organization uo ON o.id = uo.organization_id
WHERE uo.user_email = ?
`

type GetAllOrgRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetAllOrg(ctx context.Context, userEmail string) ([]GetAllOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrg, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrgRow
	for rows.Next() {
		var i GetAllOrgRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT id, name, created_at
FROM project
WHERE organization_id = ?
`

type GetAllProjectsRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetAllProjects(ctx context.Context, organizationID uuid.UUID) ([]GetAllProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProjects, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProjectsRow
	for rows.Next() {
		var i GetAllProjectsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentOrg = `-- name: GetCurrentOrg :one
SELECT o.id, o.name
FROM user u
JOIN organization o ON o.id = u.current_org_id
WHERE u.email = ?
`

type GetCurrentOrgRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetCurrentOrg(ctx context.Context, email string) (GetCurrentOrgRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentOrg, email)
	var i GetCurrentOrgRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getInstanceNetwork = `-- name: GetInstanceNetwork :one
SELECT network
FROM instance
WHERE id = ?1
`

func (q *Queries) GetInstanceNetwork(ctx context.Context, instanceID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getInstanceNetwork, instanceID)
	var network string
	err := row.Scan(&network)
	return network, err
}

const getOrgById = `-- name: GetOrgById :one
SELECT id, name FROM organization WHERE id = ?
`

type GetOrgByIdRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetOrgById(ctx context.Context, id uuid.UUID) (GetOrgByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgById, id)
	var i GetOrgByIdRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const linkUserNOrg = `-- name: LinkUserNOrg :exec
INSERT INTO user_organization (user_email, organization_id)
VALUES (?, ?)
`

type LinkUserNOrgParams struct {
	UserEmail      string    `json:"user_email"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) LinkUserNOrg(ctx context.Context, arg LinkUserNOrgParams) error {
	_, err := q.db.ExecContext(ctx, linkUserNOrg, arg.UserEmail, arg.OrganizationID)
	return err
}

const unlinkUserOrg = `-- name: UnlinkUserOrg :exec
DELETE FROM user_organization WHERE user_email = ? AND organization_id = ?
`

type UnlinkUserOrgParams struct {
	UserEmail      string    `json:"user_email"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) UnlinkUserOrg(ctx context.Context, arg UnlinkUserOrgParams) error {
	_, err := q.db.ExecContext(ctx, unlinkUserOrg, arg.UserEmail, arg.OrganizationID)
	return err
}
