// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, branch_id, commit_msg, is_current)
VALUES (?, ?, ?, ?)
RETURNING id
`

type CreateDeploymentParams struct {
	ID        uuid.UUID `json:"id"`
	BranchID  uuid.UUID `json:"branch_id"`
	CommitMsg string    `json:"commit_msg"`
	IsCurrent bool      `json:"is_current"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ID,
		arg.BranchID,
		arg.CommitMsg,
		arg.IsCurrent,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteDeploymentByID = `-- name: DeleteDeploymentByID :exec
DELETE FROM deployments
WHERE id = ?
`

func (q *Queries) DeleteDeploymentByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeploymentByID, id)
	return err
}

const downGradeDeployment = `-- name: DownGradeDeployment :exec
UPDATE deployments
SET is_current = 0, status = ?
WHERE id = ?
`

type DownGradeDeploymentParams struct {
	Status       types.DeploymentStatus `json:"status"`
	DeploymentID uuid.UUID              `json:"deployment_id"`
}

func (q *Queries) DownGradeDeployment(ctx context.Context, arg DownGradeDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, downGradeDeployment, arg.Status, arg.DeploymentID)
	return err
}

const getAllDeploymentImgByServiceID = `-- name: GetAllDeploymentImgByServiceID :many
SELECT d.id, d.image_name
FROM deployments d
JOIN app_service_branch b ON d.branch_id = b.id
WHERE b.service_id = ?
`

type GetAllDeploymentImgByServiceIDRow struct {
	ID        uuid.UUID      `json:"id"`
	ImageName sql.NullString `json:"image_name"`
}

func (q *Queries) GetAllDeploymentImgByServiceID(ctx context.Context, serviceID uuid.UUID) ([]GetAllDeploymentImgByServiceIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDeploymentImgByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDeploymentImgByServiceIDRow
	for rows.Next() {
		var i GetAllDeploymentImgByServiceIDRow
		if err := rows.Scan(&i.ID, &i.ImageName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentImgByID = `-- name: GetDeploymentImgByID :one
SELECT d.id, d.image_name
FROM deployments d
WHERE d.id = ?
`

type GetDeploymentImgByIDRow struct {
	ID        uuid.UUID      `json:"id"`
	ImageName sql.NullString `json:"image_name"`
}

func (q *Queries) GetDeploymentImgByID(ctx context.Context, id uuid.UUID) (GetDeploymentImgByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentImgByID, id)
	var i GetDeploymentImgByIDRow
	err := row.Scan(&i.ID, &i.ImageName)
	return i, err
}

const getDeploymentStatus = `-- name: GetDeploymentStatus :one
SELECT status
FROM deployments
WHERE id = ?
`

func (q *Queries) GetDeploymentStatus(ctx context.Context, id uuid.UUID) (types.DeploymentStatus, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentStatus, id)
	var status types.DeploymentStatus
	err := row.Scan(&status)
	return status, err
}

const getDeploymentsByBranchID = `-- name: GetDeploymentsByBranchID :many
SELECT d.id, d.is_current, d.image_name, d.status, b.swarm_service_name
FROM deployments d
JOIN app_service_branch b ON d.branch_id = b.id
WHERE d.branch_id = ?
ORDER BY d.created_at DESC
`

type GetDeploymentsByBranchIDRow struct {
	ID               uuid.UUID              `json:"id"`
	IsCurrent        bool                   `json:"is_current"`
	ImageName        sql.NullString         `json:"image_name"`
	Status           types.DeploymentStatus `json:"status"`
	SwarmServiceName string                 `json:"swarm_service_name"`
}

func (q *Queries) GetDeploymentsByBranchID(ctx context.Context, branchID uuid.UUID) ([]GetDeploymentsByBranchIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentsByBranchID, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentsByBranchIDRow
	for rows.Next() {
		var i GetDeploymentsByBranchIDRow
		if err := rows.Scan(
			&i.ID,
			&i.IsCurrent,
			&i.ImageName,
			&i.Status,
			&i.SwarmServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentsByServiceID = `-- name: GetDeploymentsByServiceID :many
SELECT d.id, d.status, d.commit_msg, b.branch_name, d.created_at
FROM deployments d
JOIN app_service_branch b ON d.branch_id = b.id
WHERE b.service_id = ?
ORDER BY d.created_at DESC
`

type GetDeploymentsByServiceIDRow struct {
	ID         uuid.UUID              `json:"id"`
	Status     types.DeploymentStatus `json:"status"`
	CommitMsg  string                 `json:"commit_msg"`
	BranchName string                 `json:"branch_name"`
	CreatedAt  time.Time              `json:"created_at"`
}

func (q *Queries) GetDeploymentsByServiceID(ctx context.Context, serviceID uuid.UUID) ([]GetDeploymentsByServiceIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentsByServiceIDRow
	for rows.Next() {
		var i GetDeploymentsByServiceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CommitMsg,
			&i.BranchName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeploymentImageName = `-- name: SetDeploymentImageName :exec
UPDATE deployments
SET image_name = ?
WHERE id = ?
`

type SetDeploymentImageNameParams struct {
	ImageName sql.NullString `json:"image_name"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) SetDeploymentImageName(ctx context.Context, arg SetDeploymentImageNameParams) error {
	_, err := q.db.ExecContext(ctx, setDeploymentImageName, arg.ImageName, arg.ID)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = ?
WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status types.DeploymentStatus `json:"status"`
	ID     uuid.UUID              `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.Status, arg.ID)
	return err
}

const upgradeDeployment = `-- name: UpgradeDeployment :exec
UPDATE deployments
SET is_current = 1, status = ?
WHERE id = ?
`

type UpgradeDeploymentParams struct {
	Status       types.DeploymentStatus `json:"status"`
	DeploymentID uuid.UUID              `json:"deployment_id"`
}

func (q *Queries) UpgradeDeployment(ctx context.Context, arg UpgradeDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, upgradeDeployment, arg.Status, arg.DeploymentID)
	return err
}
