// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, branch_id, commit_msg)
VALUES (?, ?, ?)
RETURNING id
`

type CreateDeploymentParams struct {
	ID        uuid.UUID `json:"id"`
	BranchID  uuid.UUID `json:"branch_id"`
	CommitMsg string    `json:"commit_msg"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createDeployment, arg.ID, arg.BranchID, arg.CommitMsg)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteDeploymentByID = `-- name: DeleteDeploymentByID :exec
DELETE FROM deployments
WHERE id = ?
`

func (q *Queries) DeleteDeploymentByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeploymentByID, id)
	return err
}

const getAllDeploymentIdsByServiceID = `-- name: GetAllDeploymentIdsByServiceID :many
SELECT d.id
FROM deployments d
JOIN app_service_branch b ON d.branch_id = b.id
WHERE b.service_id = ?
`

func (q *Queries) GetAllDeploymentIdsByServiceID(ctx context.Context, serviceID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getAllDeploymentIdsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentStatus = `-- name: GetDeploymentStatus :one
SELECT status
FROM deployments
WHERE id = ?
`

func (q *Queries) GetDeploymentStatus(ctx context.Context, id uuid.UUID) (types.DeploymentStatus, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentStatus, id)
	var status types.DeploymentStatus
	err := row.Scan(&status)
	return status, err
}

const getDeploymentsByServiceID = `-- name: GetDeploymentsByServiceID :many
SELECT d.id, d.status, d.commit_msg, b.branch_name, d.created_at
FROM deployments d
JOIN app_service_branch b ON d.branch_id = b.id
WHERE b.service_id = ?
ORDER BY created_at DESC
`

type GetDeploymentsByServiceIDRow struct {
	ID         uuid.UUID              `json:"id"`
	Status     types.DeploymentStatus `json:"status"`
	CommitMsg  string                 `json:"commit_msg"`
	BranchName string                 `json:"branch_name"`
	CreatedAt  time.Time              `json:"created_at"`
}

func (q *Queries) GetDeploymentsByServiceID(ctx context.Context, serviceID uuid.UUID) ([]GetDeploymentsByServiceIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentsByServiceIDRow
	for rows.Next() {
		var i GetDeploymentsByServiceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CommitMsg,
			&i.BranchName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeploymentImageID = `-- name: SetDeploymentImageID :exec
UPDATE deployments
SET image_id = ?
WHERE id = ?
`

type SetDeploymentImageIDParams struct {
	ImageID sql.NullString `json:"image_id"`
	ID      uuid.UUID      `json:"id"`
}

func (q *Queries) SetDeploymentImageID(ctx context.Context, arg SetDeploymentImageIDParams) error {
	_, err := q.db.ExecContext(ctx, setDeploymentImageID, arg.ImageID, arg.ID)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = ?
WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status types.DeploymentStatus `json:"status"`
	ID     uuid.UUID              `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.Status, arg.ID)
	return err
}
