// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, service_id, commit_hash, commit_msg, is_current)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateDeploymentParams struct {
	ID         uuid.UUID `json:"id"`
	ServiceID  uuid.UUID `json:"service_id"`
	CommitHash string    `json:"commit_hash"`
	CommitMsg  string    `json:"commit_msg"`
	IsCurrent  bool      `json:"is_current"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ID,
		arg.ServiceID,
		arg.CommitHash,
		arg.CommitMsg,
		arg.IsCurrent,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteDeploymentByID = `-- name: DeleteDeploymentByID :exec
DELETE FROM deployments
WHERE id = ?
`

func (q *Queries) DeleteDeploymentByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeploymentByID, id)
	return err
}

const downGradeDeployment = `-- name: DownGradeDeployment :exec
UPDATE deployments
SET is_current = FALSE, status = ?
WHERE id = ?
`

type DownGradeDeploymentParams struct {
	Status       types.DeploymentStatus `json:"status"`
	DeploymentID uuid.UUID              `json:"deployment_id"`
}

func (q *Queries) DownGradeDeployment(ctx context.Context, arg DownGradeDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, downGradeDeployment, arg.Status, arg.DeploymentID)
	return err
}

const getDeploymentImgByID = `-- name: GetDeploymentImgByID :one
SELECT d.id, d.image
FROM deployments d
WHERE d.id = ?
`

type GetDeploymentImgByIDRow struct {
	ID    uuid.UUID      `json:"id"`
	Image sql.NullString `json:"image"`
}

func (q *Queries) GetDeploymentImgByID(ctx context.Context, id uuid.UUID) (GetDeploymentImgByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentImgByID, id)
	var i GetDeploymentImgByIDRow
	err := row.Scan(&i.ID, &i.Image)
	return i, err
}

const getDeploymentStatus = `-- name: GetDeploymentStatus :one
SELECT status
FROM deployments
WHERE id = ?
`

func (q *Queries) GetDeploymentStatus(ctx context.Context, id uuid.UUID) (types.DeploymentStatus, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentStatus, id)
	var status types.DeploymentStatus
	err := row.Scan(&status)
	return status, err
}

const getDeploymentsByServiceID = `-- name: GetDeploymentsByServiceID :many
SELECT d.id, d.is_current, d.service_id, d.status, d.commit_hash, d.commit_msg, d.image, d.created_at, aps.swarm_service
FROM deployments d
JOIN app_service aps ON d.service_id = aps.id
WHERE d.service_id = ?
ORDER BY d.created_at DESC
`

type GetDeploymentsByServiceIDRow struct {
	ID           uuid.UUID              `json:"id"`
	IsCurrent    bool                   `json:"is_current"`
	ServiceID    uuid.UUID              `json:"service_id"`
	Status       types.DeploymentStatus `json:"status"`
	CommitHash   string                 `json:"commit_hash"`
	CommitMsg    string                 `json:"commit_msg"`
	Image        sql.NullString         `json:"image"`
	CreatedAt    time.Time              `json:"created_at"`
	SwarmService string                 `json:"swarm_service"`
}

func (q *Queries) GetDeploymentsByServiceID(ctx context.Context, serviceID uuid.UUID) ([]GetDeploymentsByServiceIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentsByServiceIDRow
	for rows.Next() {
		var i GetDeploymentsByServiceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.IsCurrent,
			&i.ServiceID,
			&i.Status,
			&i.CommitHash,
			&i.CommitMsg,
			&i.Image,
			&i.CreatedAt,
			&i.SwarmService,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeploymentImageName = `-- name: SetDeploymentImageName :exec
UPDATE deployments
SET image = ?
WHERE id = ?
`

type SetDeploymentImageNameParams struct {
	Image sql.NullString `json:"image"`
	ID    uuid.UUID      `json:"id"`
}

func (q *Queries) SetDeploymentImageName(ctx context.Context, arg SetDeploymentImageNameParams) error {
	_, err := q.db.ExecContext(ctx, setDeploymentImageName, arg.Image, arg.ID)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = ?
WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status types.DeploymentStatus `json:"status"`
	ID     uuid.UUID              `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.Status, arg.ID)
	return err
}

const upgradeDeployment = `-- name: UpgradeDeployment :exec
UPDATE deployments
SET is_current = TRUE, status = ?
WHERE id = ?
`

type UpgradeDeploymentParams struct {
	Status       types.DeploymentStatus `json:"status"`
	DeploymentID uuid.UUID              `json:"deployment_id"`
}

func (q *Queries) UpgradeDeployment(ctx context.Context, arg UpgradeDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, upgradeDeployment, arg.Status, arg.DeploymentID)
	return err
}
