// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const createPreviewInstance = `-- name: CreatePreviewInstance :exec
INSERT INTO instance (
    id, project_id, is_production, name, network,
    git_source_type, git_source_value, status, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePreviewInstanceParams struct {
	ID             uuid.UUID            `json:"id"`
	ProjectID      uuid.UUID            `json:"project_id"`
	IsProduction   bool                 `json:"is_production"`
	Name           string               `json:"name"`
	Network        string               `json:"network"`
	GitSourceType  types.GitSourceType  `json:"git_source_type"`
	GitSourceValue sql.NullString       `json:"git_source_value"`
	Status         types.InstanceStatus `json:"status"`
	CreatedBy      types.CreatedBy      `json:"created_by"`
}

func (q *Queries) CreatePreviewInstance(ctx context.Context, arg CreatePreviewInstanceParams) error {
	_, err := q.db.ExecContext(ctx, createPreviewInstance,
		arg.ID,
		arg.ProjectID,
		arg.IsProduction,
		arg.Name,
		arg.Network,
		arg.GitSourceType,
		arg.GitSourceValue,
		arg.Status,
		arg.CreatedBy,
	)
	return err
}

const deletePreviewInstance = `-- name: DeletePreviewInstance :exec
DELETE FROM instance
WHERE id = ?
`

func (q *Queries) DeletePreviewInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePreviewInstance, id)
	return err
}

const getActivePreviewByPR = `-- name: GetActivePreviewByPR :one
SELECT id, project_id, is_production, name, network,
    git_source_type, git_source_value, status, created_by,
    created_at
FROM instance
WHERE project_id = ? AND git_source_type = 'pr' AND git_source_value = ?
    AND status NOT IN ('deleting', 'error')
LIMIT 1
`

type GetActivePreviewByPRParams struct {
	ProjectID      uuid.UUID      `json:"project_id"`
	GitSourceValue sql.NullString `json:"git_source_value"`
}

type GetActivePreviewByPRRow struct {
	ID             uuid.UUID            `json:"id"`
	ProjectID      uuid.UUID            `json:"project_id"`
	IsProduction   bool                 `json:"is_production"`
	Name           string               `json:"name"`
	Network        string               `json:"network"`
	GitSourceType  types.GitSourceType  `json:"git_source_type"`
	GitSourceValue sql.NullString       `json:"git_source_value"`
	Status         types.InstanceStatus `json:"status"`
	CreatedBy      types.CreatedBy      `json:"created_by"`
	CreatedAt      time.Time            `json:"created_at"`
}

func (q *Queries) GetActivePreviewByPR(ctx context.Context, arg GetActivePreviewByPRParams) (GetActivePreviewByPRRow, error) {
	row := q.db.QueryRowContext(ctx, getActivePreviewByPR, arg.ProjectID, arg.GitSourceValue)
	var i GetActivePreviewByPRRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IsProduction,
		&i.Name,
		&i.Network,
		&i.GitSourceType,
		&i.GitSourceValue,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPreviewInstanceByID = `-- name: GetPreviewInstanceByID :one
SELECT id, project_id, is_production, name, network,
    git_source_type, git_source_value, status, created_by,
    created_at
FROM instance
WHERE id = ?
`

type GetPreviewInstanceByIDRow struct {
	ID             uuid.UUID            `json:"id"`
	ProjectID      uuid.UUID            `json:"project_id"`
	IsProduction   bool                 `json:"is_production"`
	Name           string               `json:"name"`
	Network        string               `json:"network"`
	GitSourceType  types.GitSourceType  `json:"git_source_type"`
	GitSourceValue sql.NullString       `json:"git_source_value"`
	Status         types.InstanceStatus `json:"status"`
	CreatedBy      types.CreatedBy      `json:"created_by"`
	CreatedAt      time.Time            `json:"created_at"`
}

func (q *Queries) GetPreviewInstanceByID(ctx context.Context, id uuid.UUID) (GetPreviewInstanceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPreviewInstanceByID, id)
	var i GetPreviewInstanceByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IsProduction,
		&i.Name,
		&i.Network,
		&i.GitSourceType,
		&i.GitSourceValue,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPreviewInstancesByProject = `-- name: GetPreviewInstancesByProject :many
SELECT id, project_id, is_production, name, network,
    git_source_type, git_source_value, status, created_by,
    created_at
FROM instance
WHERE project_id = ? AND is_production = false
ORDER BY created_at DESC
`

type GetPreviewInstancesByProjectRow struct {
	ID             uuid.UUID            `json:"id"`
	ProjectID      uuid.UUID            `json:"project_id"`
	IsProduction   bool                 `json:"is_production"`
	Name           string               `json:"name"`
	Network        string               `json:"network"`
	GitSourceType  types.GitSourceType  `json:"git_source_type"`
	GitSourceValue sql.NullString       `json:"git_source_value"`
	Status         types.InstanceStatus `json:"status"`
	CreatedBy      types.CreatedBy      `json:"created_by"`
	CreatedAt      time.Time            `json:"created_at"`
}

func (q *Queries) GetPreviewInstancesByProject(ctx context.Context, projectID uuid.UUID) ([]GetPreviewInstancesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, getPreviewInstancesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPreviewInstancesByProjectRow
	for rows.Next() {
		var i GetPreviewInstancesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IsProduction,
			&i.Name,
			&i.Network,
			&i.GitSourceType,
			&i.GitSourceValue,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductionInstanceByProject = `-- name: GetProductionInstanceByProject :one
SELECT id, project_id, is_production, name, network, created_by, created_at
FROM instance
WHERE project_id = ? AND is_production = true
LIMIT 1
`

type GetProductionInstanceByProjectRow struct {
	ID           uuid.UUID       `json:"id"`
	ProjectID    uuid.UUID       `json:"project_id"`
	IsProduction bool            `json:"is_production"`
	Name         string          `json:"name"`
	Network      string          `json:"network"`
	CreatedBy    types.CreatedBy `json:"created_by"`
	CreatedAt    time.Time       `json:"created_at"`
}

func (q *Queries) GetProductionInstanceByProject(ctx context.Context, projectID uuid.UUID) (GetProductionInstanceByProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getProductionInstanceByProject, projectID)
	var i GetProductionInstanceByProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IsProduction,
		&i.Name,
		&i.Network,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectIDByRepoID = `-- name: GetProjectIDByRepoID :one
SELECT i.project_id
FROM app_service a
JOIN instance i ON i.id = a.instance_id
WHERE a.gh_repo_id = ?
LIMIT 1
`

func (q *Queries) GetProjectIDByRepoID(ctx context.Context, ghRepoID int64) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getProjectIDByRepoID, ghRepoID)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :exec
UPDATE instance
SET status = ?
WHERE id = ?
`

type UpdateInstanceStatusParams struct {
	Status types.InstanceStatus `json:"status"`
	ID     uuid.UUID            `json:"id"`
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInstanceStatus, arg.Status, arg.ID)
	return err
}
