// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

type AppService struct {
	ID                uuid.UUID         `json:"id"`
	ProjectID         uuid.UUID         `json:"project_id"`
	Type              types.ServiceType `json:"type"`
	Name              string            `json:"name"`
	GitProvider       string            `json:"git_provider"`
	GhAppID           int64             `json:"gh_app_id"`
	GhRepoID          int64             `json:"gh_repo_id"`
	GhRepoName        string            `json:"gh_repo_name"`
	GhRepoUrl         string            `json:"gh_repo_url"`
	BuildPath         string            `json:"build_path"`
	WatchPath         string            `json:"watch_path"`
	DockerFilepath    string            `json:"docker_filepath"`
	DockerContextpath string            `json:"docker_contextpath"`
	DockerBuildstage  string            `json:"docker_buildstage"`
	Env               []byte            `json:"env"`
	BuildArgs         []byte            `json:"build_args"`
	BuildSecrets      []byte            `json:"build_secrets"`
	CreatedAt         time.Time         `json:"created_at"`
}

type AppServiceBranch struct {
	ID               uuid.UUID `json:"id"`
	ServiceID        uuid.UUID `json:"service_id"`
	IsDefaultBranch  bool      `json:"is_default_branch"`
	BranchName       string    `json:"branch_name"`
	SwarmServiceName string    `json:"swarm_service_name"`
	Domain           string    `json:"domain"`
	Port             int32     `json:"port"`
	CreatedAt        time.Time `json:"created_at"`
}

type Deployment struct {
	ID         uuid.UUID              `json:"id"`
	IsCurrent  bool                   `json:"is_current"`
	BranchID   uuid.UUID              `json:"branch_id"`
	Status     types.DeploymentStatus `json:"status"`
	CommitHash string                 `json:"commit_hash"`
	CommitMsg  string                 `json:"commit_msg"`
	ImageName  sql.NullString         `json:"image_name"`
	CreatedAt  time.Time              `json:"created_at"`
}

type GithubApp struct {
	ID             uuid.UUID     `json:"id"`
	Name           string        `json:"name"`
	OrganizationID uuid.UUID     `json:"organization_id"`
	AppID          int64         `json:"app_id"`
	InstallationID sql.NullInt64 `json:"installation_id"`
	PemKey         string        `json:"pem_key"`
	WebhookSecret  string        `json:"webhook_secret"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type Organization struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Project struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Name           string      `json:"name"`
	NetworkName    string      `json:"network_name"`
	CreatedAt      interface{} `json:"created_at"`
}

type PsqlService struct {
	ID               uuid.UUID              `json:"id"`
	ProjectID        uuid.UUID              `json:"project_id"`
	Type             types.ServiceType      `json:"type"`
	SwarmServiceID   sql.NullString         `json:"swarm_service_id"`
	SwarmServiceName string                 `json:"swarm_service_name"`
	Status           types.DeploymentStatus `json:"status"`
	Name             string                 `json:"name"`
	DbName           string                 `json:"db_name"`
	DbUser           string                 `json:"db_user"`
	DbPassword       string                 `json:"db_password"`
	ImageID          string                 `json:"image_id"`
	InternalUrl      string                 `json:"internal_url"`
	CreatedAt        time.Time              `json:"created_at"`
}

type RedirectSession struct {
	State     string        `json:"state"`
	UserID    uuid.UUID     `json:"user_id"`
	OrgID     uuid.UUID     `json:"org_id"`
	GhAppID   sql.NullInt64 `json:"gh_app_id"`
	ExpiresAt time.Time     `json:"expires_at"`
	CreatedAt time.Time     `json:"created_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	HashPass     string         `json:"hash_pass"`
	Role         types.UserRole `json:"role"`
	CurrentOrgID uuid.UUID      `json:"current_org_id"`
	CreatedAt    time.Time      `json:"created_at"`
}

type UserOrganization struct {
	UserEmail      string       `json:"user_email"`
	OrganizationID uuid.UUID    `json:"organization_id"`
	JoinedAt       sql.NullTime `json:"joined_at"`
}
