// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

type AppService struct {
	ID             uuid.UUID         `json:"id"`
	OrganizationID uuid.UUID         `json:"organization_id"`
	Type           types.ServiceType `json:"type"`
	ServiceID      string            `json:"service_id"`
	Name           string            `json:"name"`
	AppName        string            `json:"app_name"`
	Description    string            `json:"description"`
	GitProvider    string            `json:"git_provider"`
	GhAppID        int64             `json:"gh_app_id"`
	GitRepoID      string            `json:"git_repo_id"`
	GitRepoName    string            `json:"git_repo_name"`
	GitRepoUrl     string            `json:"git_repo_url"`
	DefaultBranch  string            `json:"default_branch"`
	BuildPath      string            `json:"build_path"`
	WatchPath      string            `json:"watch_path"`
	Env            string            `json:"env"`
	BuildArgs      string            `json:"build_args"`
	BuildSecrets   string            `json:"build_secrets"`
	CreatedAt      time.Time         `json:"created_at"`
}

type Deployment struct {
	ID        uuid.UUID              `json:"id"`
	ServiceID uuid.UUID              `json:"service_id"`
	Name      string                 `json:"name"`
	Status    types.DeploymentStatus `json:"status"`
	CreatedAt time.Time              `json:"created_at"`
}

type GithubApp struct {
	ID             uuid.UUID     `json:"id"`
	Name           string        `json:"name"`
	OrganizationID uuid.UUID     `json:"organization_id"`
	AppID          int64         `json:"app_id"`
	InstallationID sql.NullInt64 `json:"installation_id"`
	PemKey         string        `json:"pem_key"`
	WebhookSecret  string        `json:"webhook_secret"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type Organization struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type PsqlService struct {
	ID             uuid.UUID         `json:"id"`
	OrganizationID uuid.UUID         `json:"organization_id"`
	Type           types.ServiceType `json:"type"`
	ServiceID      string            `json:"service_id"`
	Name           string            `json:"name"`
	AppName        string            `json:"app_name"`
	Description    string            `json:"description"`
	DbName         string            `json:"db_name"`
	DbUser         string            `json:"db_user"`
	DbPassword     string            `json:"db_password"`
	Image          string            `json:"image"`
	InternalUrl    string            `json:"internal_url"`
	CreatedAt      time.Time         `json:"created_at"`
}

type RedirectSession struct {
	State     string        `json:"state"`
	UserID    uuid.UUID     `json:"user_id"`
	OrgID     uuid.UUID     `json:"org_id"`
	GhAppID   sql.NullInt64 `json:"gh_app_id"`
	ExpiresAt time.Time     `json:"expires_at"`
	CreatedAt time.Time     `json:"created_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	HashPass     string         `json:"hash_pass"`
	Role         types.UserRole `json:"role"`
	CurrentOrgID uuid.UUID      `json:"current_org_id"`
	CreatedAt    time.Time      `json:"created_at"`
}

type UserOrganization struct {
	UserEmail      string       `json:"user_email"`
	OrganizationID uuid.UUID    `json:"organization_id"`
	JoinedAt       sql.NullTime `json:"joined_at"`
}
