// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

type AppService struct {
	ID                uuid.UUID         `json:"id"`
	InstanceID        uuid.UUID         `json:"instance_id"`
	Type              types.ServiceType `json:"type"`
	Name              string            `json:"name"`
	GitProvider       types.GitProvider `json:"git_provider"`
	GhAppID           int64             `json:"gh_app_id"`
	GhRepoID          int64             `json:"gh_repo_id"`
	GhRepoName        string            `json:"gh_repo_name"`
	GhRepoUrl         string            `json:"gh_repo_url"`
	BuildPath         string            `json:"build_path"`
	WatchPath         string            `json:"watch_path"`
	DockerFilepath    string            `json:"docker_filepath"`
	DockerContextpath string            `json:"docker_contextpath"`
	DockerBuildstage  string            `json:"docker_buildstage"`
	Env               []byte            `json:"env"`
	BuildSecrets      []byte            `json:"build_secrets"`
	IsPublic          bool              `json:"is_public"`
	Branch            string            `json:"branch"`
	SwarmService      string            `json:"swarm_service"`
	Domain            sql.NullString    `json:"domain"`
	InternalUrl       string            `json:"internal_url"`
	Port              int32             `json:"port"`
	CreatedAt         time.Time         `json:"created_at"`
}

type Deployment struct {
	ID         uuid.UUID              `json:"id"`
	IsCurrent  bool                   `json:"is_current"`
	ServiceID  uuid.UUID              `json:"service_id"`
	Status     types.DeploymentStatus `json:"status"`
	CommitHash string                 `json:"commit_hash"`
	CommitMsg  string                 `json:"commit_msg"`
	Image      sql.NullString         `json:"image"`
	CreatedAt  time.Time              `json:"created_at"`
}

type GithubApp struct {
	ID             uuid.UUID     `json:"id"`
	Name           string        `json:"name"`
	OrganizationID uuid.UUID     `json:"organization_id"`
	AppID          int64         `json:"app_id"`
	InstallationID sql.NullInt64 `json:"installation_id"`
	PemKey         string        `json:"pem_key"`
	WebhookSecret  string        `json:"webhook_secret"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type GithubPullRequest struct {
	ID         uuid.UUID    `json:"id"`
	RepoID     int64        `json:"repo_id"`
	PrNumber   int64        `json:"pr_number"`
	Title      string       `json:"title"`
	HeadBranch string       `json:"head_branch"`
	BaseBranch string       `json:"base_branch"`
	State      string       `json:"state"`
	HtmlUrl    string       `json:"html_url"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type Instance struct {
	ID             uuid.UUID            `json:"id"`
	ProjectID      uuid.UUID            `json:"project_id"`
	IsProduction   bool                 `json:"is_production"`
	Name           string               `json:"name"`
	Network        string               `json:"network"`
	CreatedAt      time.Time            `json:"created_at"`
	GitSourceType  types.GitSourceType  `json:"git_source_type"`
	GitSourceValue sql.NullString       `json:"git_source_value"`
	Status         types.InstanceStatus `json:"status"`
	CreatedBy      types.CreatedBy      `json:"created_by"`
}

type Organization struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type OrphanVolume struct {
	ID             uuid.UUID               `json:"id"`
	OrganizationID uuid.UUID               `json:"organization_id"`
	DisplayName    string                  `json:"display_name"`
	Volume         string                  `json:"volume"`
	Type           types.PredefServiceType `json:"type"`
	CreatedAt      time.Time               `json:"created_at"`
}

type Project struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"created_at"`
}

type PsqlService struct {
	ID           uuid.UUID                     `json:"id"`
	InstanceID   uuid.UUID                     `json:"instance_id"`
	Status       types.PredefinedServiceStatus `json:"status"`
	Type         types.ServiceType             `json:"type"`
	Name         string                        `json:"name"`
	SwarmService string                        `json:"swarm_service"`
	DbName       string                        `json:"db_name"`
	DbUser       string                        `json:"db_user"`
	DbPassword   string                        `json:"db_password"`
	Image        string                        `json:"image"`
	Volume       string                        `json:"volume"`
	InternalUrl  string                        `json:"internal_url"`
	CreatedAt    time.Time                     `json:"created_at"`
}

type RedirectSession struct {
	State     string        `json:"state"`
	UserID    uuid.UUID     `json:"user_id"`
	OrgID     uuid.UUID     `json:"org_id"`
	GhAppID   sql.NullInt64 `json:"gh_app_id"`
	ExpiresAt time.Time     `json:"expires_at"`
	CreatedAt time.Time     `json:"created_at"`
}

type RedisService struct {
	ID           uuid.UUID                     `json:"id"`
	InstanceID   uuid.UUID                     `json:"instance_id"`
	Status       types.PredefinedServiceStatus `json:"status"`
	Type         types.ServiceType             `json:"type"`
	Name         string                        `json:"name"`
	SwarmService string                        `json:"swarm_service"`
	Password     string                        `json:"password"`
	Image        string                        `json:"image"`
	Volume       string                        `json:"volume"`
	InternalUrl  string                        `json:"internal_url"`
	CreatedAt    time.Time                     `json:"created_at"`
}

type ServiceDependency struct {
	ID              uuid.UUID `json:"id"`
	SourceServiceID uuid.UUID `json:"source_service_id"`
	TargetServiceID uuid.UUID `json:"target_service_id"`
	TargetCol       string    `json:"target_col"`
	EnvKey          string    `json:"env_key"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	HashPass     string         `json:"hash_pass"`
	Role         types.UserRole `json:"role"`
	Avatar       sql.NullString `json:"avatar"`
	CurrentOrgID uuid.UUID      `json:"current_org_id"`
	CreatedAt    time.Time      `json:"created_at"`
}

type UserOrganization struct {
	UserEmail      string       `json:"user_email"`
	OrganizationID uuid.UUID    `json:"organization_id"`
	JoinedAt       sql.NullTime `json:"joined_at"`
}
