// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: psql_service.sql

package db

import (
	"context"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const associateVolumeWithPsql = `-- name: AssociateVolumeWithPsql :exec
UPDATE psql_service
SET volume = ?
WHERE id = ?
`

type AssociateVolumeWithPsqlParams struct {
	Volume string    `json:"volume"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) AssociateVolumeWithPsql(ctx context.Context, arg AssociateVolumeWithPsqlParams) error {
	_, err := q.db.ExecContext(ctx, associateVolumeWithPsql, arg.Volume, arg.ID)
	return err
}

const claimOrphanVolume = `-- name: ClaimOrphanVolume :execrows
DELETE FROM orphan_volume
WHERE volume = ? AND organization_id = ?
`

type ClaimOrphanVolumeParams struct {
	Volume         string    `json:"volume"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ClaimOrphanVolume(ctx context.Context, arg ClaimOrphanVolumeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimOrphanVolume, arg.Volume, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createOrphanVolume = `-- name: CreateOrphanVolume :exec
INSERT INTO orphan_volume (id, organization_id, volume, type)
VALUES (?, ?, ?, ?)
`

type CreateOrphanVolumeParams struct {
	ID             uuid.UUID               `json:"id"`
	OrganizationID uuid.UUID               `json:"organization_id"`
	Volume         string                  `json:"volume"`
	Type           types.PredefServiceType `json:"type"`
}

func (q *Queries) CreateOrphanVolume(ctx context.Context, arg CreateOrphanVolumeParams) error {
	_, err := q.db.ExecContext(ctx, createOrphanVolume,
		arg.ID,
		arg.OrganizationID,
		arg.Volume,
		arg.Type,
	)
	return err
}

const createPsqlService = `-- name: CreatePsqlService :one
INSERT INTO psql_service (id, instance_id, type, swarm_service, name, db_name, db_user, db_password, internal_url, image, volume)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, type
`

type CreatePsqlServiceParams struct {
	ID           uuid.UUID         `json:"id"`
	InstanceID   uuid.UUID         `json:"instance_id"`
	Type         types.ServiceType `json:"type"`
	SwarmService string            `json:"swarm_service"`
	Name         string            `json:"name"`
	DbName       string            `json:"db_name"`
	DbUser       string            `json:"db_user"`
	DbPassword   string            `json:"db_password"`
	InternalUrl  string            `json:"internal_url"`
	Image        string            `json:"image"`
	Volume       string            `json:"volume"`
}

type CreatePsqlServiceRow struct {
	ID   uuid.UUID         `json:"id"`
	Name string            `json:"name"`
	Type types.ServiceType `json:"type"`
}

func (q *Queries) CreatePsqlService(ctx context.Context, arg CreatePsqlServiceParams) (CreatePsqlServiceRow, error) {
	row := q.db.QueryRowContext(ctx, createPsqlService,
		arg.ID,
		arg.InstanceID,
		arg.Type,
		arg.SwarmService,
		arg.Name,
		arg.DbName,
		arg.DbUser,
		arg.DbPassword,
		arg.InternalUrl,
		arg.Image,
		arg.Volume,
	)
	var i CreatePsqlServiceRow
	err := row.Scan(&i.ID, &i.Name, &i.Type)
	return i, err
}

const deleteOrphanVolume = `-- name: DeleteOrphanVolume :exec
DELETE FROM orphan_volume
WHERE volume = ? AND organization_id = ?
`

type DeleteOrphanVolumeParams struct {
	Volume         string    `json:"volume"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteOrphanVolume(ctx context.Context, arg DeleteOrphanVolumeParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanVolume, arg.Volume, arg.OrganizationID)
	return err
}

const deletePsqlService = `-- name: DeletePsqlService :exec
DELETE FROM psql_service
WHERE id = ?
`

func (q *Queries) DeletePsqlService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePsqlService, id)
	return err
}

const getAllAttachableOrphanVolumes = `-- name: GetAllAttachableOrphanVolumes :many
SELECT id, organization_id, display_name, volume, type, created_at
FROM orphan_volume
WHERE organization_id = ?
`

func (q *Queries) GetAllAttachableOrphanVolumes(ctx context.Context, organizationID uuid.UUID) ([]OrphanVolume, error) {
	rows, err := q.db.QueryContext(ctx, getAllAttachableOrphanVolumes, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanVolume
	for rows.Next() {
		var i OrphanVolume
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DisplayName,
			&i.Volume,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOrphanVolumesByOrgID = `-- name: GetAllOrphanVolumesByOrgID :many
SELECT id, organization_id, display_name, volume, type, created_at
FROM orphan_volume
WHERE organization_id = ?
`

func (q *Queries) GetAllOrphanVolumesByOrgID(ctx context.Context, organizationID uuid.UUID) ([]OrphanVolume, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrphanVolumesByOrgID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanVolume
	for rows.Next() {
		var i OrphanVolume
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DisplayName,
			&i.Volume,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrphanVolumeById = `-- name: GetOrphanVolumeById :one
SELECT id, organization_id, display_name, volume, type, created_at
FROM orphan_volume
WHERE id = ?
`

func (q *Queries) GetOrphanVolumeById(ctx context.Context, id uuid.UUID) (OrphanVolume, error) {
	row := q.db.QueryRowContext(ctx, getOrphanVolumeById, id)
	var i OrphanVolume
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.Volume,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getOrphanVolumeByName = `-- name: GetOrphanVolumeByName :one
SELECT id, organization_id, display_name, volume, type, created_at
FROM orphan_volume
WHERE volume = ?
`

func (q *Queries) GetOrphanVolumeByName(ctx context.Context, volume string) (OrphanVolume, error) {
	row := q.db.QueryRowContext(ctx, getOrphanVolumeByName, volume)
	var i OrphanVolume
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.Volume,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getOrphanVolumeByType = `-- name: GetOrphanVolumeByType :many
SELECT id, organization_id, display_name, volume, type, created_at
FROM orphan_volume
WHERE organization_id = ? AND type = ?
`

type GetOrphanVolumeByTypeParams struct {
	OrganizationID uuid.UUID               `json:"organization_id"`
	Type           types.PredefServiceType `json:"type"`
}

func (q *Queries) GetOrphanVolumeByType(ctx context.Context, arg GetOrphanVolumeByTypeParams) ([]OrphanVolume, error) {
	rows, err := q.db.QueryContext(ctx, getOrphanVolumeByType, arg.OrganizationID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanVolume
	for rows.Next() {
		var i OrphanVolume
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DisplayName,
			&i.Volume,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrphanVolumesByOrgId = `-- name: GetOrphanVolumesByOrgId :many
SELECT id, organization_id, display_name, volume, type, created_at
FROM orphan_volume
WHERE organization_id = ?
`

func (q *Queries) GetOrphanVolumesByOrgId(ctx context.Context, organizationID uuid.UUID) ([]OrphanVolume, error) {
	rows, err := q.db.QueryContext(ctx, getOrphanVolumesByOrgId, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanVolume
	for rows.Next() {
		var i OrphanVolume
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DisplayName,
			&i.Volume,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPsqlServiceById = `-- name: GetPsqlServiceById :one
SELECT ps.id, ps.instance_id, ps.type, ps.name, ps.swarm_service, ps.db_name, ps.db_user, ps.db_password, ps.image, ps.volume, ps.internal_url, ps.created_at, p.organization_id
FROM psql_service ps
JOIN instance i ON i.id = ps.instance_id
JOIN project p ON p.id = i.project_id
WHERE ps.id = ?1
`

type GetPsqlServiceByIdRow struct {
	ID             uuid.UUID         `json:"id"`
	InstanceID     uuid.UUID         `json:"instance_id"`
	Type           types.ServiceType `json:"type"`
	Name           string            `json:"name"`
	SwarmService   string            `json:"swarm_service"`
	DbName         string            `json:"db_name"`
	DbUser         string            `json:"db_user"`
	DbPassword     string            `json:"db_password"`
	Image          string            `json:"image"`
	Volume         string            `json:"volume"`
	InternalUrl    string            `json:"internal_url"`
	CreatedAt      time.Time         `json:"created_at"`
	OrganizationID uuid.UUID         `json:"organization_id"`
}

func (q *Queries) GetPsqlServiceById(ctx context.Context, serviceID uuid.UUID) (GetPsqlServiceByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPsqlServiceById, serviceID)
	var i GetPsqlServiceByIdRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Type,
		&i.Name,
		&i.SwarmService,
		&i.DbName,
		&i.DbUser,
		&i.DbPassword,
		&i.Image,
		&i.Volume,
		&i.InternalUrl,
		&i.CreatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const transferOrphanVolume = `-- name: TransferOrphanVolume :exec
UPDATE orphan_volume
SET organization_id = ?
WHERE id = ? AND organization_id = ?
`

type TransferOrphanVolumeParams struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	ID               uuid.UUID `json:"id"`
	OrganizationID_2 uuid.UUID `json:"organization_id_2"`
}

func (q *Queries) TransferOrphanVolume(ctx context.Context, arg TransferOrphanVolumeParams) error {
	_, err := q.db.ExecContext(ctx, transferOrphanVolume, arg.OrganizationID, arg.ID, arg.OrganizationID_2)
	return err
}

const updateOrphanVolumeName = `-- name: UpdateOrphanVolumeName :exec
UPDATE orphan_volume
SET display_name = ?
WHERE id = ? AND organization_id = ?
`

type UpdateOrphanVolumeNameParams struct {
	DisplayName    string    `json:"display_name"`
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) UpdateOrphanVolumeName(ctx context.Context, arg UpdateOrphanVolumeNameParams) error {
	_, err := q.db.ExecContext(ctx, updateOrphanVolumeName, arg.DisplayName, arg.ID, arg.OrganizationID)
	return err
}

const updatePsqlServiceDetails = `-- name: UpdatePsqlServiceDetails :exec
UPDATE psql_service
SET db_name = ?,
    db_user = ?,
    db_password = ?,
    internal_url = ?
WHERE id = ?
`

type UpdatePsqlServiceDetailsParams struct {
	DbName      string    `json:"db_name"`
	DbUser      string    `json:"db_user"`
	DbPassword  string    `json:"db_password"`
	InternalUrl string    `json:"internal_url"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePsqlServiceDetails(ctx context.Context, arg UpdatePsqlServiceDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updatePsqlServiceDetails,
		arg.DbName,
		arg.DbUser,
		arg.DbPassword,
		arg.InternalUrl,
		arg.ID,
	)
	return err
}
