// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: psql_service.sql

package db

import (
	"context"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const associateVolumeWithPsql = `-- name: AssociateVolumeWithPsql :exec
UPDATE psql_service
SET volume = ?
WHERE id = ?
`

type AssociateVolumeWithPsqlParams struct {
	Volume string    `json:"volume"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) AssociateVolumeWithPsql(ctx context.Context, arg AssociateVolumeWithPsqlParams) error {
	_, err := q.db.ExecContext(ctx, associateVolumeWithPsql, arg.Volume, arg.ID)
	return err
}

const createOrphanVolume = `-- name: CreateOrphanVolume :exec
INSERT INTO orphan_volume (id, organization_id, volume, type)
VALUES (?, ?, ?, ?)
`

type CreateOrphanVolumeParams struct {
	ID             uuid.UUID               `json:"id"`
	OrganizationID uuid.UUID               `json:"organization_id"`
	Volume         string                  `json:"volume"`
	Type           types.PredefServiceType `json:"type"`
}

func (q *Queries) CreateOrphanVolume(ctx context.Context, arg CreateOrphanVolumeParams) error {
	_, err := q.db.ExecContext(ctx, createOrphanVolume,
		arg.ID,
		arg.OrganizationID,
		arg.Volume,
		arg.Type,
	)
	return err
}

const createPsqlService = `-- name: CreatePsqlService :one
INSERT INTO psql_service (id, project_id, type, swarm_service_name, name, db_name, db_user, db_password, internal_url, image, volume)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreatePsqlServiceParams struct {
	ID               uuid.UUID         `json:"id"`
	ProjectID        uuid.UUID         `json:"project_id"`
	Type             types.ServiceType `json:"type"`
	SwarmServiceName string            `json:"swarm_service_name"`
	Name             string            `json:"name"`
	DbName           string            `json:"db_name"`
	DbUser           string            `json:"db_user"`
	DbPassword       string            `json:"db_password"`
	InternalUrl      string            `json:"internal_url"`
	Image            string            `json:"image"`
	Volume           string            `json:"volume"`
}

func (q *Queries) CreatePsqlService(ctx context.Context, arg CreatePsqlServiceParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createPsqlService,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.SwarmServiceName,
		arg.Name,
		arg.DbName,
		arg.DbUser,
		arg.DbPassword,
		arg.InternalUrl,
		arg.Image,
		arg.Volume,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteOrphanVolume = `-- name: DeleteOrphanVolume :exec
DELETE FROM orphan_volume
WHERE volume = ?
`

func (q *Queries) DeleteOrphanVolume(ctx context.Context, volume string) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanVolume, volume)
	return err
}

const deletePsqlService = `-- name: DeletePsqlService :exec
DELETE FROM psql_service
WHERE id = ?
`

func (q *Queries) DeletePsqlService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePsqlService, id)
	return err
}

const getAllAttachableOrphanVolumes = `-- name: GetAllAttachableOrphanVolumes :many
SELECT id, organization_id, volume, type, created_at
FROM orphan_volume
WHERE organization_id = ?
`

func (q *Queries) GetAllAttachableOrphanVolumes(ctx context.Context, organizationID uuid.UUID) ([]OrphanVolume, error) {
	rows, err := q.db.QueryContext(ctx, getAllAttachableOrphanVolumes, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanVolume
	for rows.Next() {
		var i OrphanVolume
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Volume,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOrphanVolumesByOrgID = `-- name: GetAllOrphanVolumesByOrgID :many
SELECT id, organization_id, volume, type, created_at
FROM orphan_volume
WHERE organization_id = ?
`

func (q *Queries) GetAllOrphanVolumesByOrgID(ctx context.Context, organizationID uuid.UUID) ([]OrphanVolume, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrphanVolumesByOrgID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanVolume
	for rows.Next() {
		var i OrphanVolume
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Volume,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrphanVolumeByType = `-- name: GetOrphanVolumeByType :many
SELECT id, organization_id, volume, type, created_at
FROM orphan_volume
WHERE organization_id = ? AND type = ?
`

type GetOrphanVolumeByTypeParams struct {
	OrganizationID uuid.UUID               `json:"organization_id"`
	Type           types.PredefServiceType `json:"type"`
}

func (q *Queries) GetOrphanVolumeByType(ctx context.Context, arg GetOrphanVolumeByTypeParams) ([]OrphanVolume, error) {
	rows, err := q.db.QueryContext(ctx, getOrphanVolumeByType, arg.OrganizationID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanVolume
	for rows.Next() {
		var i OrphanVolume
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Volume,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPsqlServiceById = `-- name: GetPsqlServiceById :one
SELECT ps.id, ps.project_id, ps.type, ps.name, ps.swarm_service_name, ps.db_name, ps.db_user, ps.db_password, ps.image, ps.volume, ps.internal_url, ps.created_at, pr.organization_id
FROM psql_service ps
JOIN project pr ON ps.project_id = pr.id
WHERE ps.id = ?
`

type GetPsqlServiceByIdRow struct {
	ID               uuid.UUID         `json:"id"`
	ProjectID        uuid.UUID         `json:"project_id"`
	Type             types.ServiceType `json:"type"`
	Name             string            `json:"name"`
	SwarmServiceName string            `json:"swarm_service_name"`
	DbName           string            `json:"db_name"`
	DbUser           string            `json:"db_user"`
	DbPassword       string            `json:"db_password"`
	Image            string            `json:"image"`
	Volume           string            `json:"volume"`
	InternalUrl      string            `json:"internal_url"`
	CreatedAt        time.Time         `json:"created_at"`
	OrganizationID   uuid.UUID         `json:"organization_id"`
}

func (q *Queries) GetPsqlServiceById(ctx context.Context, id uuid.UUID) (GetPsqlServiceByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPsqlServiceById, id)
	var i GetPsqlServiceByIdRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Name,
		&i.SwarmServiceName,
		&i.DbName,
		&i.DbUser,
		&i.DbPassword,
		&i.Image,
		&i.Volume,
		&i.InternalUrl,
		&i.CreatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const updatePsqlServiceDetails = `-- name: UpdatePsqlServiceDetails :exec
UPDATE psql_service
SET db_name = ?,
    db_user = ?,
    db_password = ?,
    internal_url = ?
WHERE id = ?
`

type UpdatePsqlServiceDetailsParams struct {
	DbName      string    `json:"db_name"`
	DbUser      string    `json:"db_user"`
	DbPassword  string    `json:"db_password"`
	InternalUrl string    `json:"internal_url"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePsqlServiceDetails(ctx context.Context, arg UpdatePsqlServiceDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updatePsqlServiceDetails,
		arg.DbName,
		arg.DbUser,
		arg.DbPassword,
		arg.InternalUrl,
		arg.ID,
	)
	return err
}
