// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: psql_service.sql

package db

import (
	"context"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const associateOrphanVolume = `-- name: AssociateOrphanVolume :exec
UPDATE orphan_volume
SET project_id = ?
WHERE volume = ?
`

type AssociateOrphanVolumeParams struct {
	ProjectID uuid.NullUUID `json:"project_id"`
	Volume    string        `json:"volume"`
}

func (q *Queries) AssociateOrphanVolume(ctx context.Context, arg AssociateOrphanVolumeParams) error {
	_, err := q.db.ExecContext(ctx, associateOrphanVolume, arg.ProjectID, arg.Volume)
	return err
}

const createOrphanVolume = `-- name: CreateOrphanVolume :exec
INSERT INTO orphan_volume (id, project_id, volume, type)
VALUES (?, ?, ?, ?)
`

type CreateOrphanVolumeParams struct {
	ID        uuid.UUID               `json:"id"`
	ProjectID uuid.NullUUID           `json:"project_id"`
	Volume    string                  `json:"volume"`
	Type      types.PredefServiceType `json:"type"`
}

func (q *Queries) CreateOrphanVolume(ctx context.Context, arg CreateOrphanVolumeParams) error {
	_, err := q.db.ExecContext(ctx, createOrphanVolume,
		arg.ID,
		arg.ProjectID,
		arg.Volume,
		arg.Type,
	)
	return err
}

const createPsqlService = `-- name: CreatePsqlService :one
INSERT INTO psql_service (id, project_id, type, swarm_service_name, name, db_name, db_user, db_password, internal_url, image, volume)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreatePsqlServiceParams struct {
	ID               uuid.UUID         `json:"id"`
	ProjectID        uuid.UUID         `json:"project_id"`
	Type             types.ServiceType `json:"type"`
	SwarmServiceName string            `json:"swarm_service_name"`
	Name             string            `json:"name"`
	DbName           string            `json:"db_name"`
	DbUser           string            `json:"db_user"`
	DbPassword       string            `json:"db_password"`
	InternalUrl      string            `json:"internal_url"`
	Image            string            `json:"image"`
	Volume           string            `json:"volume"`
}

func (q *Queries) CreatePsqlService(ctx context.Context, arg CreatePsqlServiceParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createPsqlService,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.SwarmServiceName,
		arg.Name,
		arg.DbName,
		arg.DbUser,
		arg.DbPassword,
		arg.InternalUrl,
		arg.Image,
		arg.Volume,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteOrphanVolume = `-- name: DeleteOrphanVolume :exec
DELETE FROM orphan_volume
WHERE volume = ?
`

func (q *Queries) DeleteOrphanVolume(ctx context.Context, volume string) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanVolume, volume)
	return err
}

const deletePsqlService = `-- name: DeletePsqlService :exec
DELETE FROM psql_service
WHERE id = ?
`

func (q *Queries) DeletePsqlService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePsqlService, id)
	return err
}

const disAssociateOrphanVolume = `-- name: DisAssociateOrphanVolume :exec
UPDATE orphan_volume
SET project_id = NULL
WHERE volume = ?
`

func (q *Queries) DisAssociateOrphanVolume(ctx context.Context, volume string) error {
	_, err := q.db.ExecContext(ctx, disAssociateOrphanVolume, volume)
	return err
}

const getAllOrphanVolumes = `-- name: GetAllOrphanVolumes :many
SELECT id, project_id, volume, type, created_at
FROM orphan_volume
WHERE project_id = ? OR project_id IS NULL
`

func (q *Queries) GetAllOrphanVolumes(ctx context.Context, projectID uuid.NullUUID) ([]OrphanVolume, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrphanVolumes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanVolume
	for rows.Next() {
		var i OrphanVolume
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Volume,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrphanVolumeByType = `-- name: GetOrphanVolumeByType :many
SELECT id, project_id, volume, type, created_at
FROM orphan_volume
WHERE (project_id = ? OR project_id IS NULL) AND type = ?
`

type GetOrphanVolumeByTypeParams struct {
	ProjectID uuid.NullUUID           `json:"project_id"`
	Type      types.PredefServiceType `json:"type"`
}

func (q *Queries) GetOrphanVolumeByType(ctx context.Context, arg GetOrphanVolumeByTypeParams) ([]OrphanVolume, error) {
	rows, err := q.db.QueryContext(ctx, getOrphanVolumeByType, arg.ProjectID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanVolume
	for rows.Next() {
		var i OrphanVolume
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Volume,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPsqlServiceById = `-- name: GetPsqlServiceById :one
SELECT id, project_id, type, name, swarm_service_name, db_name, db_user, db_password, image, volume, internal_url, created_at
FROM psql_service
WHERE id = ?
`

func (q *Queries) GetPsqlServiceById(ctx context.Context, id uuid.UUID) (PsqlService, error) {
	row := q.db.QueryRowContext(ctx, getPsqlServiceById, id)
	var i PsqlService
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Name,
		&i.SwarmServiceName,
		&i.DbName,
		&i.DbUser,
		&i.DbPassword,
		&i.Image,
		&i.Volume,
		&i.InternalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updatePsqlServiceDetails = `-- name: UpdatePsqlServiceDetails :exec
UPDATE psql_service
SET db_name = ?,
    db_user = ?,
    db_password = ?,
    internal_url = ?
WHERE id = ?
`

type UpdatePsqlServiceDetailsParams struct {
	DbName      string    `json:"db_name"`
	DbUser      string    `json:"db_user"`
	DbPassword  string    `json:"db_password"`
	InternalUrl string    `json:"internal_url"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePsqlServiceDetails(ctx context.Context, arg UpdatePsqlServiceDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updatePsqlServiceDetails,
		arg.DbName,
		arg.DbUser,
		arg.DbPassword,
		arg.InternalUrl,
		arg.ID,
	)
	return err
}
