// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: redis_service.sql

package db

import (
	"context"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const associateVolumeWithRedis = `-- name: AssociateVolumeWithRedis :exec
UPDATE redis_service
SET volume = ?
WHERE id = ?
`

type AssociateVolumeWithRedisParams struct {
	Volume string    `json:"volume"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) AssociateVolumeWithRedis(ctx context.Context, arg AssociateVolumeWithRedisParams) error {
	_, err := q.db.ExecContext(ctx, associateVolumeWithRedis, arg.Volume, arg.ID)
	return err
}

const createRedisService = `-- name: CreateRedisService :one
INSERT INTO redis_service (id, instance_id, type, swarm_service, name, password, internal_url, image, volume)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, type
`

type CreateRedisServiceParams struct {
	ID           uuid.UUID         `json:"id"`
	InstanceID   uuid.UUID         `json:"instance_id"`
	Type         types.ServiceType `json:"type"`
	SwarmService string            `json:"swarm_service"`
	Name         string            `json:"name"`
	Password     string            `json:"password"`
	InternalUrl  string            `json:"internal_url"`
	Image        string            `json:"image"`
	Volume       string            `json:"volume"`
}

type CreateRedisServiceRow struct {
	ID   uuid.UUID         `json:"id"`
	Name string            `json:"name"`
	Type types.ServiceType `json:"type"`
}

func (q *Queries) CreateRedisService(ctx context.Context, arg CreateRedisServiceParams) (CreateRedisServiceRow, error) {
	row := q.db.QueryRowContext(ctx, createRedisService,
		arg.ID,
		arg.InstanceID,
		arg.Type,
		arg.SwarmService,
		arg.Name,
		arg.Password,
		arg.InternalUrl,
		arg.Image,
		arg.Volume,
	)
	var i CreateRedisServiceRow
	err := row.Scan(&i.ID, &i.Name, &i.Type)
	return i, err
}

const deleteRedisService = `-- name: DeleteRedisService :exec
DELETE FROM redis_service
WHERE id = ?
`

func (q *Queries) DeleteRedisService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRedisService, id)
	return err
}

const getRedisServiceById = `-- name: GetRedisServiceById :one
SELECT rs.id, rs.instance_id, rs.type, rs.name, rs.swarm_service, rs.password, rs.image, rs.volume, rs.internal_url, rs.created_at, rs.status, p.organization_id
FROM redis_service rs
JOIN instance i ON i.id = rs.instance_id
JOIN project p ON p.id = i.project_id
WHERE rs.id = ?1
`

type GetRedisServiceByIdRow struct {
	ID             uuid.UUID         `json:"id"`
	InstanceID     uuid.UUID         `json:"instance_id"`
	Type           types.ServiceType `json:"type"`
	Name           string            `json:"name"`
	SwarmService   string            `json:"swarm_service"`
	Password       string            `json:"password"`
	Image          string            `json:"image"`
	Volume         string            `json:"volume"`
	InternalUrl    string            `json:"internal_url"`
	CreatedAt      time.Time         `json:"created_at"`
	Status         string            `json:"status"`
	OrganizationID uuid.UUID         `json:"organization_id"`
}

func (q *Queries) GetRedisServiceById(ctx context.Context, serviceID uuid.UUID) (GetRedisServiceByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getRedisServiceById, serviceID)
	var i GetRedisServiceByIdRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Type,
		&i.Name,
		&i.SwarmService,
		&i.Password,
		&i.Image,
		&i.Volume,
		&i.InternalUrl,
		&i.CreatedAt,
		&i.Status,
		&i.OrganizationID,
	)
	return i, err
}

const updateRedisServiceDetails = `-- name: UpdateRedisServiceDetails :exec
UPDATE redis_service
SET password = ?,
    internal_url = ?
WHERE id = ?
`

type UpdateRedisServiceDetailsParams struct {
	Password    string    `json:"password"`
	InternalUrl string    `json:"internal_url"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateRedisServiceDetails(ctx context.Context, arg UpdateRedisServiceDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateRedisServiceDetails, arg.Password, arg.InternalUrl, arg.ID)
	return err
}
