// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const checkProjectHasService = `-- name: CheckProjectHasService :one
SELECT CAST(EXISTS(
    SELECT 1
    FROM app_service aps
    JOIN instance i ON i.id = aps.instance_id
    WHERE i.project_id = ?1
    UNION ALL
    SELECT 1
    FROM psql_service ps
    JOIN instance i ON i.id = ps.instance_id
    WHERE i.project_id = ?1
) AS BOOLEAN)
`

func (q *Queries) CheckProjectHasService(ctx context.Context, projectID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectHasService, projectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkServiceIsProduction = `-- name: CheckServiceIsProduction :one
SELECT is_production
FROM app_service aps
JOIN instance i ON i.id = aps.instance_id
WHERE aps.id = ?1
`

func (q *Queries) CheckServiceIsProduction(ctx context.Context, serviceID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkServiceIsProduction, serviceID)
	var is_production bool
	err := row.Scan(&is_production)
	return is_production, err
}

const createAppService = `-- name: CreateAppService :one
INSERT INTO app_service (id, instance_id, type, name, git_provider, gh_app_id, gh_repo_id, gh_repo_name, gh_repo_url, build_path, watch_path, env, build_args, build_secrets, docker_filepath, docker_contextpath, docker_buildstage, is_public, branch, swarm_service, port, internal_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, type
`

type CreateAppServiceParams struct {
	ID                uuid.UUID         `json:"id"`
	InstanceID        uuid.UUID         `json:"instance_id"`
	Type              types.ServiceType `json:"type"`
	Name              string            `json:"name"`
	GitProvider       string            `json:"git_provider"`
	GhAppID           int64             `json:"gh_app_id"`
	GhRepoID          int64             `json:"gh_repo_id"`
	GhRepoName        string            `json:"gh_repo_name"`
	GhRepoUrl         string            `json:"gh_repo_url"`
	BuildPath         string            `json:"build_path"`
	WatchPath         string            `json:"watch_path"`
	Env               []byte            `json:"env"`
	BuildArgs         []byte            `json:"build_args"`
	BuildSecrets      []byte            `json:"build_secrets"`
	DockerFilepath    string            `json:"docker_filepath"`
	DockerContextpath string            `json:"docker_contextpath"`
	DockerBuildstage  string            `json:"docker_buildstage"`
	IsPublic          bool              `json:"is_public"`
	Branch            string            `json:"branch"`
	SwarmService      string            `json:"swarm_service"`
	Port              int32             `json:"port"`
	InternalUrl       string            `json:"internal_url"`
}

type CreateAppServiceRow struct {
	ID   uuid.UUID         `json:"id"`
	Name string            `json:"name"`
	Type types.ServiceType `json:"type"`
}

func (q *Queries) CreateAppService(ctx context.Context, arg CreateAppServiceParams) (CreateAppServiceRow, error) {
	row := q.db.QueryRowContext(ctx, createAppService,
		arg.ID,
		arg.InstanceID,
		arg.Type,
		arg.Name,
		arg.GitProvider,
		arg.GhAppID,
		arg.GhRepoID,
		arg.GhRepoName,
		arg.GhRepoUrl,
		arg.BuildPath,
		arg.WatchPath,
		arg.Env,
		arg.BuildArgs,
		arg.BuildSecrets,
		arg.DockerFilepath,
		arg.DockerContextpath,
		arg.DockerBuildstage,
		arg.IsPublic,
		arg.Branch,
		arg.SwarmService,
		arg.Port,
		arg.InternalUrl,
	)
	var i CreateAppServiceRow
	err := row.Scan(&i.ID, &i.Name, &i.Type)
	return i, err
}

const deleteAppService = `-- name: DeleteAppService :exec
DELETE FROM app_service
WHERE id = ?
`

func (q *Queries) DeleteAppService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAppService, id)
	return err
}

const getAllAppServicesByRepo = `-- name: GetAllAppServicesByRepo :many
SELECT a.id AS service_id, a.name, a.gh_repo_url, a.gh_app_id,
    a.build_path, a.watch_path, a.env, a.build_args, a.build_secrets,
    a.docker_filepath, a.docker_contextpath, a.docker_buildstage,
    a.branch, a.swarm_service, a.domain, a.port,
    d.id AS deployment_id, d.status AS deployment_status
FROM app_service a
JOIN deployments d ON d.service_id = a.id AND d.is_current
WHERE a.gh_repo_id = ? AND a.branch = ?
`

type GetAllAppServicesByRepoParams struct {
	GhRepoID int64  `json:"gh_repo_id"`
	Branch   string `json:"branch"`
}

type GetAllAppServicesByRepoRow struct {
	ServiceID         uuid.UUID              `json:"service_id"`
	Name              string                 `json:"name"`
	GhRepoUrl         string                 `json:"gh_repo_url"`
	GhAppID           int64                  `json:"gh_app_id"`
	BuildPath         string                 `json:"build_path"`
	WatchPath         string                 `json:"watch_path"`
	Env               []byte                 `json:"env"`
	BuildArgs         []byte                 `json:"build_args"`
	BuildSecrets      []byte                 `json:"build_secrets"`
	DockerFilepath    string                 `json:"docker_filepath"`
	DockerContextpath string                 `json:"docker_contextpath"`
	DockerBuildstage  string                 `json:"docker_buildstage"`
	Branch            string                 `json:"branch"`
	SwarmService      string                 `json:"swarm_service"`
	Domain            string                 `json:"domain"`
	Port              int32                  `json:"port"`
	DeploymentID      uuid.UUID              `json:"deployment_id"`
	DeploymentStatus  types.DeploymentStatus `json:"deployment_status"`
}

func (q *Queries) GetAllAppServicesByRepo(ctx context.Context, arg GetAllAppServicesByRepoParams) ([]GetAllAppServicesByRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAppServicesByRepo, arg.GhRepoID, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAppServicesByRepoRow
	for rows.Next() {
		var i GetAllAppServicesByRepoRow
		if err := rows.Scan(
			&i.ServiceID,
			&i.Name,
			&i.GhRepoUrl,
			&i.GhAppID,
			&i.BuildPath,
			&i.WatchPath,
			&i.Env,
			&i.BuildArgs,
			&i.BuildSecrets,
			&i.DockerFilepath,
			&i.DockerContextpath,
			&i.DockerBuildstage,
			&i.Branch,
			&i.SwarmService,
			&i.Domain,
			&i.Port,
			&i.DeploymentID,
			&i.DeploymentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllService = `-- name: GetAllService :many
SELECT ps.id, ps.type, ps.name, '' AS gh_repo_name, '' AS gh_repo_url, '' AS git_provider, '' AS branch_name, ps.created_at
FROM psql_service ps
WHERE ps.instance_id = ?1
UNION ALL
SELECT aps.id, aps.type, aps.name, aps.gh_repo_url, aps.gh_repo_url, aps.git_provider, aps.branch, aps.created_at
FROM app_service aps
WHERE aps.instance_id = ?1
`

type GetAllServiceRow struct {
	ID          uuid.UUID         `json:"id"`
	Type        types.ServiceType `json:"type"`
	Name        string            `json:"name"`
	GhRepoName  string            `json:"gh_repo_name"`
	GhRepoUrl   string            `json:"gh_repo_url"`
	GitProvider string            `json:"git_provider"`
	BranchName  string            `json:"branch_name"`
	CreatedAt   time.Time         `json:"created_at"`
}

func (q *Queries) GetAllService(ctx context.Context, instanceID uuid.UUID) ([]GetAllServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllService, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllServiceRow
	for rows.Next() {
		var i GetAllServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.GhRepoName,
			&i.GhRepoUrl,
			&i.GitProvider,
			&i.BranchName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSwarmServiceAndImgByAppServiceId = `-- name: GetAllSwarmServiceAndImgByAppServiceId :many
SELECT aps.swarm_service, d.id AS deployment_id, d.image
FROM app_service aps
JOIN deployments d ON d.service_id = aps.id
WHERE aps.id = ?1
`

type GetAllSwarmServiceAndImgByAppServiceIdRow struct {
	SwarmService string         `json:"swarm_service"`
	DeploymentID uuid.UUID      `json:"deployment_id"`
	Image        sql.NullString `json:"image"`
}

func (q *Queries) GetAllSwarmServiceAndImgByAppServiceId(ctx context.Context, serviceID uuid.UUID) ([]GetAllSwarmServiceAndImgByAppServiceIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSwarmServiceAndImgByAppServiceId, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSwarmServiceAndImgByAppServiceIdRow
	for rows.Next() {
		var i GetAllSwarmServiceAndImgByAppServiceIdRow
		if err := rows.Scan(&i.SwarmService, &i.DeploymentID, &i.Image); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppServiceById = `-- name: GetAppServiceById :one
SELECT
    a.id, a.instance_id, a.type, a.name, a.git_provider, a.gh_app_id, a.gh_repo_id, a.gh_repo_name, a.gh_repo_url, a.build_path, a.watch_path, a.docker_filepath, a.docker_contextpath, a.docker_buildstage, a.env, a.build_args, a.build_secrets, a.is_public, a.branch, a.swarm_service, a.domain, a.internal_url, a.port, a.created_at,
    d.id AS deployment_id,d.status AS deployment_status, d.commit_msg
FROM app_service a
JOIN deployments d ON d.service_id = a.id AND d.is_current
WHERE a.id = ?
`

type GetAppServiceByIdRow struct {
	ID                uuid.UUID              `json:"id"`
	InstanceID        uuid.UUID              `json:"instance_id"`
	Type              types.ServiceType      `json:"type"`
	Name              string                 `json:"name"`
	GitProvider       string                 `json:"git_provider"`
	GhAppID           int64                  `json:"gh_app_id"`
	GhRepoID          int64                  `json:"gh_repo_id"`
	GhRepoName        string                 `json:"gh_repo_name"`
	GhRepoUrl         string                 `json:"gh_repo_url"`
	BuildPath         string                 `json:"build_path"`
	WatchPath         string                 `json:"watch_path"`
	DockerFilepath    string                 `json:"docker_filepath"`
	DockerContextpath string                 `json:"docker_contextpath"`
	DockerBuildstage  string                 `json:"docker_buildstage"`
	Env               []byte                 `json:"env"`
	BuildArgs         []byte                 `json:"build_args"`
	BuildSecrets      []byte                 `json:"build_secrets"`
	IsPublic          bool                   `json:"is_public"`
	Branch            string                 `json:"branch"`
	SwarmService      string                 `json:"swarm_service"`
	Domain            string                 `json:"domain"`
	InternalUrl       string                 `json:"internal_url"`
	Port              int32                  `json:"port"`
	CreatedAt         time.Time              `json:"created_at"`
	DeploymentID      uuid.UUID              `json:"deployment_id"`
	DeploymentStatus  types.DeploymentStatus `json:"deployment_status"`
	CommitMsg         string                 `json:"commit_msg"`
}

func (q *Queries) GetAppServiceById(ctx context.Context, id uuid.UUID) (GetAppServiceByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAppServiceById, id)
	var i GetAppServiceByIdRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Type,
		&i.Name,
		&i.GitProvider,
		&i.GhAppID,
		&i.GhRepoID,
		&i.GhRepoName,
		&i.GhRepoUrl,
		&i.BuildPath,
		&i.WatchPath,
		&i.DockerFilepath,
		&i.DockerContextpath,
		&i.DockerBuildstage,
		&i.Env,
		&i.BuildArgs,
		&i.BuildSecrets,
		&i.IsPublic,
		&i.Branch,
		&i.SwarmService,
		&i.Domain,
		&i.InternalUrl,
		&i.Port,
		&i.CreatedAt,
		&i.DeploymentID,
		&i.DeploymentStatus,
		&i.CommitMsg,
	)
	return i, err
}

const getDomainAndPortByServiceId = `-- name: GetDomainAndPortByServiceId :one
SELECT domain, port
FROM app_service
WHERE id = ?1
`

type GetDomainAndPortByServiceIdRow struct {
	Domain string `json:"domain"`
	Port   int32  `json:"port"`
}

func (q *Queries) GetDomainAndPortByServiceId(ctx context.Context, serviceID uuid.UUID) (GetDomainAndPortByServiceIdRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainAndPortByServiceId, serviceID)
	var i GetDomainAndPortByServiceIdRow
	err := row.Scan(&i.Domain, &i.Port)
	return i, err
}

const getServiceEnv = `-- name: GetServiceEnv :one
SELECT env, build_args, build_secrets
FROM app_service
WHERE id = ?
`

type GetServiceEnvRow struct {
	Env          []byte `json:"env"`
	BuildArgs    []byte `json:"build_args"`
	BuildSecrets []byte `json:"build_secrets"`
}

func (q *Queries) GetServiceEnv(ctx context.Context, id uuid.UUID) (GetServiceEnvRow, error) {
	row := q.db.QueryRowContext(ctx, getServiceEnv, id)
	var i GetServiceEnvRow
	err := row.Scan(&i.Env, &i.BuildArgs, &i.BuildSecrets)
	return i, err
}

const getServiceID = `-- name: GetServiceID :one
SELECT ps.id 
FROM psql_service ps
WHERE ps.instance_id = ?1 AND ps.name = ?2
UNION ALL
SELECT aps.id 
FROM app_service aps
WHERE aps.instance_id = ?1 AND aps.name = ?2
`

type GetServiceIDParams struct {
	InstanceID uuid.UUID `json:"instance_id"`
	Name       string    `json:"name"`
}

func (q *Queries) GetServiceID(ctx context.Context, arg GetServiceIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getServiceID, arg.InstanceID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSwarmServiceByServiceId = `-- name: GetSwarmServiceByServiceId :one
SELECT swarm_service
FROM app_service aps
WHERE aps.id = ?1
UNION ALL
SELECT swarm_service
FROM psql_service ps
WHERE ps.id = ?1
`

func (q *Queries) GetSwarmServiceByServiceId(ctx context.Context, serviceID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getSwarmServiceByServiceId, serviceID)
	var swarm_service string
	err := row.Scan(&swarm_service)
	return swarm_service, err
}

const serviceNameExists = `-- name: ServiceNameExists :one
SELECT CAST(
    (SELECT EXISTS (
        SELECT 1
        FROM psql_service ps
        WHERE ps.instance_id = ?1 AND ps.name = ?2
        UNION ALL
        SELECT 1
        FROM app_service aps
        WHERE aps.instance_id = ?1 AND aps.name = ?2
    ))
AS BOOLEAN)
`

type ServiceNameExistsParams struct {
	InstanceID uuid.UUID `json:"instance_id"`
	Name       string    `json:"name"`
}

func (q *Queries) ServiceNameExists(ctx context.Context, arg ServiceNameExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, serviceNameExists, arg.InstanceID, arg.Name)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAppServiceEnv = `-- name: UpdateAppServiceEnv :exec
UPDATE app_service
SET env = ?, build_args = ?, build_secrets = ?
WHERE id = ?
`

type UpdateAppServiceEnvParams struct {
	Env          []byte    `json:"env"`
	BuildArgs    []byte    `json:"build_args"`
	BuildSecrets []byte    `json:"build_secrets"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAppServiceEnv(ctx context.Context, arg UpdateAppServiceEnvParams) error {
	_, err := q.db.ExecContext(ctx, updateAppServiceEnv,
		arg.Env,
		arg.BuildArgs,
		arg.BuildSecrets,
		arg.ID,
	)
	return err
}

const updateDomianAndPort = `-- name: UpdateDomianAndPort :exec
UPDATE app_service
SET domain = ?, port = ?
WHERE id = ?
`

type UpdateDomianAndPortParams struct {
	Domain    string    `json:"domain"`
	Port      int32     `json:"port"`
	ServiceID uuid.UUID `json:"service_id"`
}

func (q *Queries) UpdateDomianAndPort(ctx context.Context, arg UpdateDomianAndPortParams) error {
	_, err := q.db.ExecContext(ctx, updateDomianAndPort, arg.Domain, arg.Port, arg.ServiceID)
	return err
}
