// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service.sql

package db

import (
	"context"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const createAppService = `-- name: CreateAppService :one
INSERT INTO app_service (id, project_id, type, service_id, name, app_name, description, git_provider, gh_app_id, git_repo_id, git_repo_name, git_repo_url, git_branch, build_path, watch_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, type
`

type CreateAppServiceParams struct {
	ID          uuid.UUID         `json:"id"`
	ProjectID   uuid.UUID         `json:"project_id"`
	Type        types.ServiceType `json:"type"`
	ServiceID   string            `json:"service_id"`
	Name        string            `json:"name"`
	AppName     string            `json:"app_name"`
	Description string            `json:"description"`
	GitProvider string            `json:"git_provider"`
	GhAppID     int64             `json:"gh_app_id"`
	GitRepoID   string            `json:"git_repo_id"`
	GitRepoName string            `json:"git_repo_name"`
	GitRepoUrl  string            `json:"git_repo_url"`
	GitBranch   string            `json:"git_branch"`
	BuildPath   string            `json:"build_path"`
	WatchPath   string            `json:"watch_path"`
}

type CreateAppServiceRow struct {
	ID   uuid.UUID         `json:"id"`
	Type types.ServiceType `json:"type"`
}

func (q *Queries) CreateAppService(ctx context.Context, arg CreateAppServiceParams) (CreateAppServiceRow, error) {
	row := q.db.QueryRowContext(ctx, createAppService,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.ServiceID,
		arg.Name,
		arg.AppName,
		arg.Description,
		arg.GitProvider,
		arg.GhAppID,
		arg.GitRepoID,
		arg.GitRepoName,
		arg.GitRepoUrl,
		arg.GitBranch,
		arg.BuildPath,
		arg.WatchPath,
	)
	var i CreateAppServiceRow
	err := row.Scan(&i.ID, &i.Type)
	return i, err
}

const createPsqlService = `-- name: CreatePsqlService :one
INSERT INTO psql_service (id, project_id, type, service_id, name, app_name, description, db_name, db_user, db_password, image, internal_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, type
`

type CreatePsqlServiceParams struct {
	ID          uuid.UUID         `json:"id"`
	ProjectID   uuid.UUID         `json:"project_id"`
	Type        types.ServiceType `json:"type"`
	ServiceID   string            `json:"service_id"`
	Name        string            `json:"name"`
	AppName     string            `json:"app_name"`
	Description string            `json:"description"`
	DbName      string            `json:"db_name"`
	DbUser      string            `json:"db_user"`
	DbPassword  string            `json:"db_password"`
	Image       string            `json:"image"`
	InternalUrl string            `json:"internal_url"`
}

type CreatePsqlServiceRow struct {
	ID   uuid.UUID         `json:"id"`
	Type types.ServiceType `json:"type"`
}

func (q *Queries) CreatePsqlService(ctx context.Context, arg CreatePsqlServiceParams) (CreatePsqlServiceRow, error) {
	row := q.db.QueryRowContext(ctx, createPsqlService,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.ServiceID,
		arg.Name,
		arg.AppName,
		arg.Description,
		arg.DbName,
		arg.DbUser,
		arg.DbPassword,
		arg.Image,
		arg.InternalUrl,
	)
	var i CreatePsqlServiceRow
	err := row.Scan(&i.ID, &i.Type)
	return i, err
}

const deleteAppService = `-- name: DeleteAppService :exec
DELETE FROM app_service
WHERE id = ?
`

func (q *Queries) DeleteAppService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAppService, id)
	return err
}

const deletePsqlService = `-- name: DeletePsqlService :exec
DELETE FROM psql_service
WHERE id = ?
`

func (q *Queries) DeletePsqlService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePsqlService, id)
	return err
}

const getAllPsqlServicesByProjectId = `-- name: GetAllPsqlServicesByProjectId :many
SELECT id, project_id, type, service_id, name, app_name, description, db_name, db_user, db_password, image, internal_url, created_at
FROM psql_service
WHERE project_id = ?
`

func (q *Queries) GetAllPsqlServicesByProjectId(ctx context.Context, projectID uuid.UUID) ([]PsqlService, error) {
	rows, err := q.db.QueryContext(ctx, getAllPsqlServicesByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsqlService
	for rows.Next() {
		var i PsqlService
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.ServiceID,
			&i.Name,
			&i.AppName,
			&i.Description,
			&i.DbName,
			&i.DbUser,
			&i.DbPassword,
			&i.Image,
			&i.InternalUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllServicesByOrgId = `-- name: GetAllServicesByOrgId :many
SELECT ps.id, ps.type, ps.name, ps.description, ps.created_at
FROM psql_service ps
JOIN project p ON p.id = ps.project_id
WHERE p.organization_id = ?1
UNION ALL
SELECT aps.id, aps.type, aps.name, aps.description, aps.created_at
FROM app_service aps
JOIN project p ON p.id = aps.project_id
WHERE p.organization_id = ?1
`

type GetAllServicesByOrgIdRow struct {
	ID          uuid.UUID         `json:"id"`
	Type        types.ServiceType `json:"type"`
	Name        string            `json:"name"`
	Description string            `json:"description"`
	CreatedAt   time.Time         `json:"created_at"`
}

func (q *Queries) GetAllServicesByOrgId(ctx context.Context, orgID uuid.UUID) ([]GetAllServicesByOrgIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllServicesByOrgId, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllServicesByOrgIdRow
	for rows.Next() {
		var i GetAllServicesByOrgIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllServicesByProjectId = `-- name: GetAllServicesByProjectId :many
SELECT id, type, name, description, created_at
FROM psql_service ps
WHERE ps.project_id = ?1
UNION ALL
SELECT id, type, name, description, created_at
FROM app_service aps
WHERE aps.project_id = ?1
`

type GetAllServicesByProjectIdRow struct {
	ID          uuid.UUID         `json:"id"`
	Type        types.ServiceType `json:"type"`
	Name        string            `json:"name"`
	Description string            `json:"description"`
	CreatedAt   time.Time         `json:"created_at"`
}

func (q *Queries) GetAllServicesByProjectId(ctx context.Context, projectid uuid.UUID) ([]GetAllServicesByProjectIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllServicesByProjectId, projectid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllServicesByProjectIdRow
	for rows.Next() {
		var i GetAllServicesByProjectIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppServiceById = `-- name: GetAppServiceById :one
SELECT id, project_id, type, service_id, name, app_name, description, git_provider, gh_app_id, git_repo_id, git_repo_name, git_repo_url, git_branch, build_path, watch_path, created_at
FROM app_service
WHERE id = ?
`

func (q *Queries) GetAppServiceById(ctx context.Context, id uuid.UUID) (AppService, error) {
	row := q.db.QueryRowContext(ctx, getAppServiceById, id)
	var i AppService
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.ServiceID,
		&i.Name,
		&i.AppName,
		&i.Description,
		&i.GitProvider,
		&i.GhAppID,
		&i.GitRepoID,
		&i.GitRepoName,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.BuildPath,
		&i.WatchPath,
		&i.CreatedAt,
	)
	return i, err
}

const getPsqlServiceById = `-- name: GetPsqlServiceById :one
SELECT id, project_id, type, service_id, name, app_name, description, db_name, db_user, db_password, image, internal_url, created_at
FROM psql_service
WHERE id = ?
`

func (q *Queries) GetPsqlServiceById(ctx context.Context, id uuid.UUID) (PsqlService, error) {
	row := q.db.QueryRowContext(ctx, getPsqlServiceById, id)
	var i PsqlService
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.ServiceID,
		&i.Name,
		&i.AppName,
		&i.Description,
		&i.DbName,
		&i.DbUser,
		&i.DbPassword,
		&i.Image,
		&i.InternalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const setAppServiceId = `-- name: SetAppServiceId :exec
UPDATE app_service
SET service_id = ?
WHERE id = ?
`

type SetAppServiceIdParams struct {
	ServiceID string    `json:"service_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SetAppServiceId(ctx context.Context, arg SetAppServiceIdParams) error {
	_, err := q.db.ExecContext(ctx, setAppServiceId, arg.ServiceID, arg.ID)
	return err
}

const setPsqlServiceId = `-- name: SetPsqlServiceId :exec
UPDATE psql_service
SET service_id = ?
WHERE id = ?
`

type SetPsqlServiceIdParams struct {
	ServiceID string    `json:"service_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SetPsqlServiceId(ctx context.Context, arg SetPsqlServiceIdParams) error {
	_, err := q.db.ExecContext(ctx, setPsqlServiceId, arg.ServiceID, arg.ID)
	return err
}

const updateAppServiceDetails = `-- name: UpdateAppServiceDetails :exec
UPDATE app_service
SET git_provider = ?,
    gh_app_id = ?,
    git_repo_id = ?,
    git_repo_name = ?,
    git_repo_url = ?,
    git_branch = ?,
    build_path = ?,
    watch_path = ?
WHERE id = ?
`

type UpdateAppServiceDetailsParams struct {
	GitProvider string    `json:"git_provider"`
	GhAppID     int64     `json:"gh_app_id"`
	GitRepoID   string    `json:"git_repo_id"`
	GitRepoName string    `json:"git_repo_name"`
	GitRepoUrl  string    `json:"git_repo_url"`
	GitBranch   string    `json:"git_branch"`
	BuildPath   string    `json:"build_path"`
	WatchPath   string    `json:"watch_path"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAppServiceDetails(ctx context.Context, arg UpdateAppServiceDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateAppServiceDetails,
		arg.GitProvider,
		arg.GhAppID,
		arg.GitRepoID,
		arg.GitRepoName,
		arg.GitRepoUrl,
		arg.GitBranch,
		arg.BuildPath,
		arg.WatchPath,
		arg.ID,
	)
	return err
}
