// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const adminExists = `-- name: AdminExists :one
SELECT CAST(EXISTS (
    SELECT 1 FROM user
    WHERE role = 'admin'
) AS BOOLEAN)
`

func (q *Queries) AdminExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, adminExists)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO user (id, name, email, hash_pass, role, current_org_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateUserParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	HashPass     string         `json:"hash_pass"`
	Role         types.UserRole `json:"role"`
	CurrentOrgID uuid.UUID      `json:"current_org_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.HashPass,
		arg.Role,
		arg.CurrentOrgID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
   u.id,
   u.name,
   u.email,
   u.hash_pass,
   u.role,
   o.id AS org_id,
   o.name AS org_name
FROM user u
JOIN organization o ON o.id = u.current_org_id
WHERE u.email = ?
`

type GetUserByEmailRow struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	HashPass string         `json:"hash_pass"`
	Role     types.UserRole `json:"role"`
	OrgID    uuid.UUID      `json:"org_id"`
	OrgName  string         `json:"org_name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashPass,
		&i.Role,
		&i.OrgID,
		&i.OrgName,
	)
	return i, err
}

const getUserCurrentOrg = `-- name: GetUserCurrentOrg :one
SELECT u.current_org_id
FROM user u
WHERE u.email = ?
`

func (q *Queries) GetUserCurrentOrg(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserCurrentOrg, email)
	var current_org_id uuid.UUID
	err := row.Scan(&current_org_id)
	return current_org_id, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, name, email, role, avatar, created_at
FROM user
WHERE id = ?
`

type GetUserProfileRow struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Role      types.UserRole `json:"role"`
	Avatar    string         `json:"avatar"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Avatar,
		&i.CreatedAt,
	)
	return i, err
}

const isUserAdmin = `-- name: IsUserAdmin :one
SELECT CAST(EXISTS (
    SELECT 1 FROM user
    WHERE email = ? AND role = 'admin'
) AS BOOLEAN)
`

func (q *Queries) IsUserAdmin(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserAdmin, email)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateCurrentOrg = `-- name: UpdateCurrentOrg :exec
UPDATE user
SET current_org_id = ?
WHERE id = ?
`

type UpdateCurrentOrgParams struct {
	CurrentOrgID uuid.UUID `json:"current_org_id"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCurrentOrg(ctx context.Context, arg UpdateCurrentOrgParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrentOrg, arg.CurrentOrgID, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE user
SET hash_pass = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	HashPass string    `json:"hash_pass"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.HashPass, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE user
SET name = ?, email = ?, avatar = ?
WHERE id = ?
`

type UpdateUserProfileParams struct {
	Name   string    `json:"name"`
	Email  string    `json:"email"`
	Avatar string    `json:"avatar"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Name,
		arg.Email,
		arg.Avatar,
		arg.ID,
	)
	return err
}
